// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface AsrEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AsrEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>double start_s = 2;</code>
   * @return The startS.
   */
  double getStartS();

  /**
   * <code>double end_s = 3;</code>
   * @return The endS.
   */
  double getEndS();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>.AsrType type = 5;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.AsrType type = 5;</code>
   * @return The type.
   */
  samuraibff.proto.AsrType getType();

  /**
   * <pre>
   * optional (e.g., "cs")
   * </pre>
   *
   * <code>string lang = 6;</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <pre>
   * optional (e.g., "cs")
   * </pre>
   *
   * <code>string lang = 6;</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>string speaker = 7;</code>
   * @return The speaker.
   */
  java.lang.String getSpeaker();
  /**
   * <code>string speaker = 7;</code>
   * @return The bytes for speaker.
   */
  com.google.protobuf.ByteString
      getSpeakerBytes();
}
