// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * Protobuf type {@code AsyncTrackPlan}
 */
@com.google.protobuf.Generated
public final class AsyncTrackPlan extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AsyncTrackPlan)
    AsyncTrackPlanOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "AsyncTrackPlan");
  }
  // Use AsyncTrackPlan.newBuilder() to construct.
  private AsyncTrackPlan(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AsyncTrackPlan() {
    planId_ = "";
    tenantId_ = "";
    sessionId_ = "";
    finalTracks_ = java.util.Collections.emptyList();
    refinementTracks_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_AsyncTrackPlan_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_AsyncTrackPlan_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.AsyncTrackPlan.class, samuraibff.proto.AsyncTrackPlan.Builder.class);
  }

  public static final int SCHEMA_VERSION_FIELD_NUMBER = 1;
  private int schemaVersion_ = 0;
  /**
   * <code>uint32 schema_version = 1 [json_name = "schemaVersion"];</code>
   * @return The schemaVersion.
   */
  @java.lang.Override
  public int getSchemaVersion() {
    return schemaVersion_;
  }

  public static final int PLAN_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object planId_ = "";
  /**
   * <code>string plan_id = 2 [json_name = "planId"];</code>
   * @return The planId.
   */
  @java.lang.Override
  public java.lang.String getPlanId() {
    java.lang.Object ref = planId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      planId_ = s;
      return s;
    }
  }
  /**
   * <code>string plan_id = 2 [json_name = "planId"];</code>
   * @return The bytes for planId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlanIdBytes() {
    java.lang.Object ref = planId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      planId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 4 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 4 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FINAL_TRACKS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<samuraibff.proto.AsyncTrackSelection> finalTracks_;
  /**
   * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
   */
  @java.lang.Override
  public java.util.List<samuraibff.proto.AsyncTrackSelection> getFinalTracksList() {
    return finalTracks_;
  }
  /**
   * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends samuraibff.proto.AsyncTrackSelectionOrBuilder> 
      getFinalTracksOrBuilderList() {
    return finalTracks_;
  }
  /**
   * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
   */
  @java.lang.Override
  public int getFinalTracksCount() {
    return finalTracks_.size();
  }
  /**
   * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
   */
  @java.lang.Override
  public samuraibff.proto.AsyncTrackSelection getFinalTracks(int index) {
    return finalTracks_.get(index);
  }
  /**
   * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
   */
  @java.lang.Override
  public samuraibff.proto.AsyncTrackSelectionOrBuilder getFinalTracksOrBuilder(
      int index) {
    return finalTracks_.get(index);
  }

  public static final int REFINEMENT_TRACKS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<samuraibff.proto.AsyncTrackSelection> refinementTracks_;
  /**
   * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
   */
  @java.lang.Override
  public java.util.List<samuraibff.proto.AsyncTrackSelection> getRefinementTracksList() {
    return refinementTracks_;
  }
  /**
   * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends samuraibff.proto.AsyncTrackSelectionOrBuilder> 
      getRefinementTracksOrBuilderList() {
    return refinementTracks_;
  }
  /**
   * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
   */
  @java.lang.Override
  public int getRefinementTracksCount() {
    return refinementTracks_.size();
  }
  /**
   * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
   */
  @java.lang.Override
  public samuraibff.proto.AsyncTrackSelection getRefinementTracks(int index) {
    return refinementTracks_.get(index);
  }
  /**
   * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
   */
  @java.lang.Override
  public samuraibff.proto.AsyncTrackSelectionOrBuilder getRefinementTracksOrBuilder(
      int index) {
    return refinementTracks_.get(index);
  }

  public static final int REFINEMENT_WINDOW_SAMPLES_FIELD_NUMBER = 7;
  private long refinementWindowSamples_ = 0L;
  /**
   * <code>uint64 refinement_window_samples = 7 [json_name = "refinementWindowSamples"];</code>
   * @return The refinementWindowSamples.
   */
  @java.lang.Override
  public long getRefinementWindowSamples() {
    return refinementWindowSamples_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schemaVersion_ != 0) {
      output.writeUInt32(1, schemaVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(planId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, planId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, sessionId_);
    }
    for (int i = 0; i < finalTracks_.size(); i++) {
      output.writeMessage(5, finalTracks_.get(i));
    }
    for (int i = 0; i < refinementTracks_.size(); i++) {
      output.writeMessage(6, refinementTracks_.get(i));
    }
    if (refinementWindowSamples_ != 0L) {
      output.writeUInt64(7, refinementWindowSamples_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schemaVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, schemaVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(planId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, planId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, sessionId_);
    }
    for (int i = 0; i < finalTracks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, finalTracks_.get(i));
    }
    for (int i = 0; i < refinementTracks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, refinementTracks_.get(i));
    }
    if (refinementWindowSamples_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, refinementWindowSamples_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.AsyncTrackPlan)) {
      return super.equals(obj);
    }
    samuraibff.proto.AsyncTrackPlan other = (samuraibff.proto.AsyncTrackPlan) obj;

    if (getSchemaVersion()
        != other.getSchemaVersion()) return false;
    if (!getPlanId()
        .equals(other.getPlanId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getFinalTracksList()
        .equals(other.getFinalTracksList())) return false;
    if (!getRefinementTracksList()
        .equals(other.getRefinementTracksList())) return false;
    if (getRefinementWindowSamples()
        != other.getRefinementWindowSamples()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEMA_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaVersion();
    hash = (37 * hash) + PLAN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPlanId().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    if (getFinalTracksCount() > 0) {
      hash = (37 * hash) + FINAL_TRACKS_FIELD_NUMBER;
      hash = (53 * hash) + getFinalTracksList().hashCode();
    }
    if (getRefinementTracksCount() > 0) {
      hash = (37 * hash) + REFINEMENT_TRACKS_FIELD_NUMBER;
      hash = (53 * hash) + getRefinementTracksList().hashCode();
    }
    hash = (37 * hash) + REFINEMENT_WINDOW_SAMPLES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRefinementWindowSamples());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.AsyncTrackPlan parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.AsyncTrackPlan parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.AsyncTrackPlan parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.AsyncTrackPlan prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AsyncTrackPlan}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AsyncTrackPlan)
      samuraibff.proto.AsyncTrackPlanOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_AsyncTrackPlan_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_AsyncTrackPlan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.AsyncTrackPlan.class, samuraibff.proto.AsyncTrackPlan.Builder.class);
    }

    // Construct using samuraibff.proto.AsyncTrackPlan.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      schemaVersion_ = 0;
      planId_ = "";
      tenantId_ = "";
      sessionId_ = "";
      if (finalTracksBuilder_ == null) {
        finalTracks_ = java.util.Collections.emptyList();
      } else {
        finalTracks_ = null;
        finalTracksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (refinementTracksBuilder_ == null) {
        refinementTracks_ = java.util.Collections.emptyList();
      } else {
        refinementTracks_ = null;
        refinementTracksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      refinementWindowSamples_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_AsyncTrackPlan_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.AsyncTrackPlan getDefaultInstanceForType() {
      return samuraibff.proto.AsyncTrackPlan.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.AsyncTrackPlan build() {
      samuraibff.proto.AsyncTrackPlan result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.AsyncTrackPlan buildPartial() {
      samuraibff.proto.AsyncTrackPlan result = new samuraibff.proto.AsyncTrackPlan(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(samuraibff.proto.AsyncTrackPlan result) {
      if (finalTracksBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          finalTracks_ = java.util.Collections.unmodifiableList(finalTracks_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.finalTracks_ = finalTracks_;
      } else {
        result.finalTracks_ = finalTracksBuilder_.build();
      }
      if (refinementTracksBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          refinementTracks_ = java.util.Collections.unmodifiableList(refinementTracks_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.refinementTracks_ = refinementTracks_;
      } else {
        result.refinementTracks_ = refinementTracksBuilder_.build();
      }
    }

    private void buildPartial0(samuraibff.proto.AsyncTrackPlan result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.schemaVersion_ = schemaVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.planId_ = planId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.refinementWindowSamples_ = refinementWindowSamples_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.AsyncTrackPlan) {
        return mergeFrom((samuraibff.proto.AsyncTrackPlan)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.AsyncTrackPlan other) {
      if (other == samuraibff.proto.AsyncTrackPlan.getDefaultInstance()) return this;
      if (other.getSchemaVersion() != 0) {
        setSchemaVersion(other.getSchemaVersion());
      }
      if (!other.getPlanId().isEmpty()) {
        planId_ = other.planId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (finalTracksBuilder_ == null) {
        if (!other.finalTracks_.isEmpty()) {
          if (finalTracks_.isEmpty()) {
            finalTracks_ = other.finalTracks_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFinalTracksIsMutable();
            finalTracks_.addAll(other.finalTracks_);
          }
          onChanged();
        }
      } else {
        if (!other.finalTracks_.isEmpty()) {
          if (finalTracksBuilder_.isEmpty()) {
            finalTracksBuilder_.dispose();
            finalTracksBuilder_ = null;
            finalTracks_ = other.finalTracks_;
            bitField0_ = (bitField0_ & ~0x00000010);
            finalTracksBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetFinalTracksFieldBuilder() : null;
          } else {
            finalTracksBuilder_.addAllMessages(other.finalTracks_);
          }
        }
      }
      if (refinementTracksBuilder_ == null) {
        if (!other.refinementTracks_.isEmpty()) {
          if (refinementTracks_.isEmpty()) {
            refinementTracks_ = other.refinementTracks_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureRefinementTracksIsMutable();
            refinementTracks_.addAll(other.refinementTracks_);
          }
          onChanged();
        }
      } else {
        if (!other.refinementTracks_.isEmpty()) {
          if (refinementTracksBuilder_.isEmpty()) {
            refinementTracksBuilder_.dispose();
            refinementTracksBuilder_ = null;
            refinementTracks_ = other.refinementTracks_;
            bitField0_ = (bitField0_ & ~0x00000020);
            refinementTracksBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRefinementTracksFieldBuilder() : null;
          } else {
            refinementTracksBuilder_.addAllMessages(other.refinementTracks_);
          }
        }
      }
      if (other.getRefinementWindowSamples() != 0L) {
        setRefinementWindowSamples(other.getRefinementWindowSamples());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              schemaVersion_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              planId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              samuraibff.proto.AsyncTrackSelection m =
                  input.readMessage(
                      samuraibff.proto.AsyncTrackSelection.parser(),
                      extensionRegistry);
              if (finalTracksBuilder_ == null) {
                ensureFinalTracksIsMutable();
                finalTracks_.add(m);
              } else {
                finalTracksBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              samuraibff.proto.AsyncTrackSelection m =
                  input.readMessage(
                      samuraibff.proto.AsyncTrackSelection.parser(),
                      extensionRegistry);
              if (refinementTracksBuilder_ == null) {
                ensureRefinementTracksIsMutable();
                refinementTracks_.add(m);
              } else {
                refinementTracksBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 56: {
              refinementWindowSamples_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int schemaVersion_ ;
    /**
     * <code>uint32 schema_version = 1 [json_name = "schemaVersion"];</code>
     * @return The schemaVersion.
     */
    @java.lang.Override
    public int getSchemaVersion() {
      return schemaVersion_;
    }
    /**
     * <code>uint32 schema_version = 1 [json_name = "schemaVersion"];</code>
     * @param value The schemaVersion to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaVersion(int value) {

      schemaVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 schema_version = 1 [json_name = "schemaVersion"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      schemaVersion_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object planId_ = "";
    /**
     * <code>string plan_id = 2 [json_name = "planId"];</code>
     * @return The planId.
     */
    public java.lang.String getPlanId() {
      java.lang.Object ref = planId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        planId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plan_id = 2 [json_name = "planId"];</code>
     * @return The bytes for planId.
     */
    public com.google.protobuf.ByteString
        getPlanIdBytes() {
      java.lang.Object ref = planId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        planId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plan_id = 2 [json_name = "planId"];</code>
     * @param value The planId to set.
     * @return This builder for chaining.
     */
    public Builder setPlanId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      planId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string plan_id = 2 [json_name = "planId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPlanId() {
      planId_ = getDefaultInstance().getPlanId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string plan_id = 2 [json_name = "planId"];</code>
     * @param value The bytes for planId to set.
     * @return This builder for chaining.
     */
    public Builder setPlanIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      planId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 4 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 4 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 4 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 4 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 4 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<samuraibff.proto.AsyncTrackSelection> finalTracks_ =
      java.util.Collections.emptyList();
    private void ensureFinalTracksIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        finalTracks_ = new java.util.ArrayList<samuraibff.proto.AsyncTrackSelection>(finalTracks_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.AsyncTrackSelection, samuraibff.proto.AsyncTrackSelection.Builder, samuraibff.proto.AsyncTrackSelectionOrBuilder> finalTracksBuilder_;

    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public java.util.List<samuraibff.proto.AsyncTrackSelection> getFinalTracksList() {
      if (finalTracksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(finalTracks_);
      } else {
        return finalTracksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public int getFinalTracksCount() {
      if (finalTracksBuilder_ == null) {
        return finalTracks_.size();
      } else {
        return finalTracksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection getFinalTracks(int index) {
      if (finalTracksBuilder_ == null) {
        return finalTracks_.get(index);
      } else {
        return finalTracksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder setFinalTracks(
        int index, samuraibff.proto.AsyncTrackSelection value) {
      if (finalTracksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFinalTracksIsMutable();
        finalTracks_.set(index, value);
        onChanged();
      } else {
        finalTracksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder setFinalTracks(
        int index, samuraibff.proto.AsyncTrackSelection.Builder builderForValue) {
      if (finalTracksBuilder_ == null) {
        ensureFinalTracksIsMutable();
        finalTracks_.set(index, builderForValue.build());
        onChanged();
      } else {
        finalTracksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder addFinalTracks(samuraibff.proto.AsyncTrackSelection value) {
      if (finalTracksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFinalTracksIsMutable();
        finalTracks_.add(value);
        onChanged();
      } else {
        finalTracksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder addFinalTracks(
        int index, samuraibff.proto.AsyncTrackSelection value) {
      if (finalTracksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFinalTracksIsMutable();
        finalTracks_.add(index, value);
        onChanged();
      } else {
        finalTracksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder addFinalTracks(
        samuraibff.proto.AsyncTrackSelection.Builder builderForValue) {
      if (finalTracksBuilder_ == null) {
        ensureFinalTracksIsMutable();
        finalTracks_.add(builderForValue.build());
        onChanged();
      } else {
        finalTracksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder addFinalTracks(
        int index, samuraibff.proto.AsyncTrackSelection.Builder builderForValue) {
      if (finalTracksBuilder_ == null) {
        ensureFinalTracksIsMutable();
        finalTracks_.add(index, builderForValue.build());
        onChanged();
      } else {
        finalTracksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder addAllFinalTracks(
        java.lang.Iterable<? extends samuraibff.proto.AsyncTrackSelection> values) {
      if (finalTracksBuilder_ == null) {
        ensureFinalTracksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, finalTracks_);
        onChanged();
      } else {
        finalTracksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder clearFinalTracks() {
      if (finalTracksBuilder_ == null) {
        finalTracks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        finalTracksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public Builder removeFinalTracks(int index) {
      if (finalTracksBuilder_ == null) {
        ensureFinalTracksIsMutable();
        finalTracks_.remove(index);
        onChanged();
      } else {
        finalTracksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection.Builder getFinalTracksBuilder(
        int index) {
      return internalGetFinalTracksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelectionOrBuilder getFinalTracksOrBuilder(
        int index) {
      if (finalTracksBuilder_ == null) {
        return finalTracks_.get(index);  } else {
        return finalTracksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public java.util.List<? extends samuraibff.proto.AsyncTrackSelectionOrBuilder> 
         getFinalTracksOrBuilderList() {
      if (finalTracksBuilder_ != null) {
        return finalTracksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(finalTracks_);
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection.Builder addFinalTracksBuilder() {
      return internalGetFinalTracksFieldBuilder().addBuilder(
          samuraibff.proto.AsyncTrackSelection.getDefaultInstance());
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection.Builder addFinalTracksBuilder(
        int index) {
      return internalGetFinalTracksFieldBuilder().addBuilder(
          index, samuraibff.proto.AsyncTrackSelection.getDefaultInstance());
    }
    /**
     * <code>repeated .AsyncTrackSelection final_tracks = 5 [json_name = "finalTracks"];</code>
     */
    public java.util.List<samuraibff.proto.AsyncTrackSelection.Builder> 
         getFinalTracksBuilderList() {
      return internalGetFinalTracksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.AsyncTrackSelection, samuraibff.proto.AsyncTrackSelection.Builder, samuraibff.proto.AsyncTrackSelectionOrBuilder> 
        internalGetFinalTracksFieldBuilder() {
      if (finalTracksBuilder_ == null) {
        finalTracksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            samuraibff.proto.AsyncTrackSelection, samuraibff.proto.AsyncTrackSelection.Builder, samuraibff.proto.AsyncTrackSelectionOrBuilder>(
                finalTracks_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        finalTracks_ = null;
      }
      return finalTracksBuilder_;
    }

    private java.util.List<samuraibff.proto.AsyncTrackSelection> refinementTracks_ =
      java.util.Collections.emptyList();
    private void ensureRefinementTracksIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        refinementTracks_ = new java.util.ArrayList<samuraibff.proto.AsyncTrackSelection>(refinementTracks_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.AsyncTrackSelection, samuraibff.proto.AsyncTrackSelection.Builder, samuraibff.proto.AsyncTrackSelectionOrBuilder> refinementTracksBuilder_;

    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public java.util.List<samuraibff.proto.AsyncTrackSelection> getRefinementTracksList() {
      if (refinementTracksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(refinementTracks_);
      } else {
        return refinementTracksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public int getRefinementTracksCount() {
      if (refinementTracksBuilder_ == null) {
        return refinementTracks_.size();
      } else {
        return refinementTracksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection getRefinementTracks(int index) {
      if (refinementTracksBuilder_ == null) {
        return refinementTracks_.get(index);
      } else {
        return refinementTracksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder setRefinementTracks(
        int index, samuraibff.proto.AsyncTrackSelection value) {
      if (refinementTracksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRefinementTracksIsMutable();
        refinementTracks_.set(index, value);
        onChanged();
      } else {
        refinementTracksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder setRefinementTracks(
        int index, samuraibff.proto.AsyncTrackSelection.Builder builderForValue) {
      if (refinementTracksBuilder_ == null) {
        ensureRefinementTracksIsMutable();
        refinementTracks_.set(index, builderForValue.build());
        onChanged();
      } else {
        refinementTracksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder addRefinementTracks(samuraibff.proto.AsyncTrackSelection value) {
      if (refinementTracksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRefinementTracksIsMutable();
        refinementTracks_.add(value);
        onChanged();
      } else {
        refinementTracksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder addRefinementTracks(
        int index, samuraibff.proto.AsyncTrackSelection value) {
      if (refinementTracksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRefinementTracksIsMutable();
        refinementTracks_.add(index, value);
        onChanged();
      } else {
        refinementTracksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder addRefinementTracks(
        samuraibff.proto.AsyncTrackSelection.Builder builderForValue) {
      if (refinementTracksBuilder_ == null) {
        ensureRefinementTracksIsMutable();
        refinementTracks_.add(builderForValue.build());
        onChanged();
      } else {
        refinementTracksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder addRefinementTracks(
        int index, samuraibff.proto.AsyncTrackSelection.Builder builderForValue) {
      if (refinementTracksBuilder_ == null) {
        ensureRefinementTracksIsMutable();
        refinementTracks_.add(index, builderForValue.build());
        onChanged();
      } else {
        refinementTracksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder addAllRefinementTracks(
        java.lang.Iterable<? extends samuraibff.proto.AsyncTrackSelection> values) {
      if (refinementTracksBuilder_ == null) {
        ensureRefinementTracksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, refinementTracks_);
        onChanged();
      } else {
        refinementTracksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder clearRefinementTracks() {
      if (refinementTracksBuilder_ == null) {
        refinementTracks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        refinementTracksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public Builder removeRefinementTracks(int index) {
      if (refinementTracksBuilder_ == null) {
        ensureRefinementTracksIsMutable();
        refinementTracks_.remove(index);
        onChanged();
      } else {
        refinementTracksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection.Builder getRefinementTracksBuilder(
        int index) {
      return internalGetRefinementTracksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelectionOrBuilder getRefinementTracksOrBuilder(
        int index) {
      if (refinementTracksBuilder_ == null) {
        return refinementTracks_.get(index);  } else {
        return refinementTracksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public java.util.List<? extends samuraibff.proto.AsyncTrackSelectionOrBuilder> 
         getRefinementTracksOrBuilderList() {
      if (refinementTracksBuilder_ != null) {
        return refinementTracksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(refinementTracks_);
      }
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection.Builder addRefinementTracksBuilder() {
      return internalGetRefinementTracksFieldBuilder().addBuilder(
          samuraibff.proto.AsyncTrackSelection.getDefaultInstance());
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public samuraibff.proto.AsyncTrackSelection.Builder addRefinementTracksBuilder(
        int index) {
      return internalGetRefinementTracksFieldBuilder().addBuilder(
          index, samuraibff.proto.AsyncTrackSelection.getDefaultInstance());
    }
    /**
     * <code>repeated .AsyncTrackSelection refinement_tracks = 6 [json_name = "refinementTracks"];</code>
     */
    public java.util.List<samuraibff.proto.AsyncTrackSelection.Builder> 
         getRefinementTracksBuilderList() {
      return internalGetRefinementTracksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.AsyncTrackSelection, samuraibff.proto.AsyncTrackSelection.Builder, samuraibff.proto.AsyncTrackSelectionOrBuilder> 
        internalGetRefinementTracksFieldBuilder() {
      if (refinementTracksBuilder_ == null) {
        refinementTracksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            samuraibff.proto.AsyncTrackSelection, samuraibff.proto.AsyncTrackSelection.Builder, samuraibff.proto.AsyncTrackSelectionOrBuilder>(
                refinementTracks_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        refinementTracks_ = null;
      }
      return refinementTracksBuilder_;
    }

    private long refinementWindowSamples_ ;
    /**
     * <code>uint64 refinement_window_samples = 7 [json_name = "refinementWindowSamples"];</code>
     * @return The refinementWindowSamples.
     */
    @java.lang.Override
    public long getRefinementWindowSamples() {
      return refinementWindowSamples_;
    }
    /**
     * <code>uint64 refinement_window_samples = 7 [json_name = "refinementWindowSamples"];</code>
     * @param value The refinementWindowSamples to set.
     * @return This builder for chaining.
     */
    public Builder setRefinementWindowSamples(long value) {

      refinementWindowSamples_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 refinement_window_samples = 7 [json_name = "refinementWindowSamples"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRefinementWindowSamples() {
      bitField0_ = (bitField0_ & ~0x00000040);
      refinementWindowSamples_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AsyncTrackPlan)
  }

  // @@protoc_insertion_point(class_scope:AsyncTrackPlan)
  private static final samuraibff.proto.AsyncTrackPlan DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.AsyncTrackPlan();
  }

  public static samuraibff.proto.AsyncTrackPlan getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AsyncTrackPlan>
      PARSER = new com.google.protobuf.AbstractParser<AsyncTrackPlan>() {
    @java.lang.Override
    public AsyncTrackPlan parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AsyncTrackPlan> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AsyncTrackPlan> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.AsyncTrackPlan getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

