// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface AsyncTrackSelectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AsyncTrackSelection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string track_id = 1 [json_name = "trackId"];</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <code>string track_id = 1 [json_name = "trackId"];</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <code>string profile_id = 2 [json_name = "profileId"];</code>
   * @return The profileId.
   */
  java.lang.String getProfileId();
  /**
   * <code>string profile_id = 2 [json_name = "profileId"];</code>
   * @return The bytes for profileId.
   */
  com.google.protobuf.ByteString
      getProfileIdBytes();

  /**
   * <code>bool primary = 3 [json_name = "primary"];</code>
   * @return The primary.
   */
  boolean getPrimary();
}
