// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * <pre>
 * Frozen by the BFF before accepting audio; clients cannot supply profiles.
 * </pre>
 *
 * Protobuf type {@code AsyncTrackSelection}
 */
@com.google.protobuf.Generated
public final class AsyncTrackSelection extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AsyncTrackSelection)
    AsyncTrackSelectionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "AsyncTrackSelection");
  }
  // Use AsyncTrackSelection.newBuilder() to construct.
  private AsyncTrackSelection(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AsyncTrackSelection() {
    trackId_ = "";
    profileId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_AsyncTrackSelection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_AsyncTrackSelection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.AsyncTrackSelection.class, samuraibff.proto.AsyncTrackSelection.Builder.class);
  }

  public static final int TRACK_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object trackId_ = "";
  /**
   * <code>string track_id = 1 [json_name = "trackId"];</code>
   * @return The trackId.
   */
  @java.lang.Override
  public java.lang.String getTrackId() {
    java.lang.Object ref = trackId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      trackId_ = s;
      return s;
    }
  }
  /**
   * <code>string track_id = 1 [json_name = "trackId"];</code>
   * @return The bytes for trackId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTrackIdBytes() {
    java.lang.Object ref = trackId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      trackId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROFILE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object profileId_ = "";
  /**
   * <code>string profile_id = 2 [json_name = "profileId"];</code>
   * @return The profileId.
   */
  @java.lang.Override
  public java.lang.String getProfileId() {
    java.lang.Object ref = profileId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profileId_ = s;
      return s;
    }
  }
  /**
   * <code>string profile_id = 2 [json_name = "profileId"];</code>
   * @return The bytes for profileId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProfileIdBytes() {
    java.lang.Object ref = profileId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profileId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIMARY_FIELD_NUMBER = 3;
  private boolean primary_ = false;
  /**
   * <code>bool primary = 3 [json_name = "primary"];</code>
   * @return The primary.
   */
  @java.lang.Override
  public boolean getPrimary() {
    return primary_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, trackId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(profileId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, profileId_);
    }
    if (primary_ != false) {
      output.writeBool(3, primary_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, trackId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(profileId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, profileId_);
    }
    if (primary_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, primary_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.AsyncTrackSelection)) {
      return super.equals(obj);
    }
    samuraibff.proto.AsyncTrackSelection other = (samuraibff.proto.AsyncTrackSelection) obj;

    if (!getTrackId()
        .equals(other.getTrackId())) return false;
    if (!getProfileId()
        .equals(other.getProfileId())) return false;
    if (getPrimary()
        != other.getPrimary()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRACK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTrackId().hashCode();
    hash = (37 * hash) + PROFILE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProfileId().hashCode();
    hash = (37 * hash) + PRIMARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPrimary());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.AsyncTrackSelection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.AsyncTrackSelection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.AsyncTrackSelection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.AsyncTrackSelection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Frozen by the BFF before accepting audio; clients cannot supply profiles.
   * </pre>
   *
   * Protobuf type {@code AsyncTrackSelection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AsyncTrackSelection)
      samuraibff.proto.AsyncTrackSelectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_AsyncTrackSelection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_AsyncTrackSelection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.AsyncTrackSelection.class, samuraibff.proto.AsyncTrackSelection.Builder.class);
    }

    // Construct using samuraibff.proto.AsyncTrackSelection.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trackId_ = "";
      profileId_ = "";
      primary_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_AsyncTrackSelection_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.AsyncTrackSelection getDefaultInstanceForType() {
      return samuraibff.proto.AsyncTrackSelection.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.AsyncTrackSelection build() {
      samuraibff.proto.AsyncTrackSelection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.AsyncTrackSelection buildPartial() {
      samuraibff.proto.AsyncTrackSelection result = new samuraibff.proto.AsyncTrackSelection(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(samuraibff.proto.AsyncTrackSelection result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trackId_ = trackId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.profileId_ = profileId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.primary_ = primary_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.AsyncTrackSelection) {
        return mergeFrom((samuraibff.proto.AsyncTrackSelection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.AsyncTrackSelection other) {
      if (other == samuraibff.proto.AsyncTrackSelection.getDefaultInstance()) return this;
      if (!other.getTrackId().isEmpty()) {
        trackId_ = other.trackId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getProfileId().isEmpty()) {
        profileId_ = other.profileId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getPrimary() != false) {
        setPrimary(other.getPrimary());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              trackId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              profileId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              primary_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object trackId_ = "";
    /**
     * <code>string track_id = 1 [json_name = "trackId"];</code>
     * @return The trackId.
     */
    public java.lang.String getTrackId() {
      java.lang.Object ref = trackId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trackId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string track_id = 1 [json_name = "trackId"];</code>
     * @return The bytes for trackId.
     */
    public com.google.protobuf.ByteString
        getTrackIdBytes() {
      java.lang.Object ref = trackId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trackId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string track_id = 1 [json_name = "trackId"];</code>
     * @param value The trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      trackId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string track_id = 1 [json_name = "trackId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackId() {
      trackId_ = getDefaultInstance().getTrackId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string track_id = 1 [json_name = "trackId"];</code>
     * @param value The bytes for trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      trackId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object profileId_ = "";
    /**
     * <code>string profile_id = 2 [json_name = "profileId"];</code>
     * @return The profileId.
     */
    public java.lang.String getProfileId() {
      java.lang.Object ref = profileId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profileId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string profile_id = 2 [json_name = "profileId"];</code>
     * @return The bytes for profileId.
     */
    public com.google.protobuf.ByteString
        getProfileIdBytes() {
      java.lang.Object ref = profileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string profile_id = 2 [json_name = "profileId"];</code>
     * @param value The profileId to set.
     * @return This builder for chaining.
     */
    public Builder setProfileId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      profileId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string profile_id = 2 [json_name = "profileId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProfileId() {
      profileId_ = getDefaultInstance().getProfileId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string profile_id = 2 [json_name = "profileId"];</code>
     * @param value The bytes for profileId to set.
     * @return This builder for chaining.
     */
    public Builder setProfileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      profileId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean primary_ ;
    /**
     * <code>bool primary = 3 [json_name = "primary"];</code>
     * @return The primary.
     */
    @java.lang.Override
    public boolean getPrimary() {
      return primary_;
    }
    /**
     * <code>bool primary = 3 [json_name = "primary"];</code>
     * @param value The primary to set.
     * @return This builder for chaining.
     */
    public Builder setPrimary(boolean value) {

      primary_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool primary = 3 [json_name = "primary"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPrimary() {
      bitField0_ = (bitField0_ & ~0x00000004);
      primary_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AsyncTrackSelection)
  }

  // @@protoc_insertion_point(class_scope:AsyncTrackSelection)
  private static final samuraibff.proto.AsyncTrackSelection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.AsyncTrackSelection();
  }

  public static samuraibff.proto.AsyncTrackSelection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AsyncTrackSelection>
      PARSER = new com.google.protobuf.AbstractParser<AsyncTrackSelection>() {
    @java.lang.Override
    public AsyncTrackSelection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AsyncTrackSelection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AsyncTrackSelection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.AsyncTrackSelection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

