// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface AudioChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AudioChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * incremental per session
   * </pre>
   *
   * <code>uint64 seq = 2;</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <pre>
   * producer monotonic timestamp OR sample time
   * </pre>
   *
   * <code>int64 t0_ns = 3;</code>
   * @return The t0Ns.
   */
  long getT0Ns();

  /**
   * <pre>
   * 16000
   * </pre>
   *
   * <code>uint32 sample_rate = 4;</code>
   * @return The sampleRate.
   */
  int getSampleRate();

  /**
   * <pre>
   * little-endian PCM16 mono
   * </pre>
   *
   * <code>bytes pcm16_le = 5;</code>
   * @return The pcm16Le.
   */
  com.google.protobuf.ByteString getPcm16Le();

  /**
   * <code>string lang = 6;</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 6;</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <pre>
   * Base URI of the BFF instance that originated this session.
   * Used as a "reply-to" for refined events when Kafka partitions
   * distribute consumption across multiple BFF instances.
   * Example: "http://bff-1.internal:8000".
   * </pre>
   *
   * <code>string bff_origin_uri = 7;</code>
   * @return The bffOriginUri.
   */
  java.lang.String getBffOriginUri();
  /**
   * <pre>
   * Base URI of the BFF instance that originated this session.
   * Used as a "reply-to" for refined events when Kafka partitions
   * distribute consumption across multiple BFF instances.
   * Example: "http://bff-1.internal:8000".
   * </pre>
   *
   * <code>string bff_origin_uri = 7;</code>
   * @return The bytes for bffOriginUri.
   */
  com.google.protobuf.ByteString
      getBffOriginUriBytes();

  /**
   * <pre>
   * Tenant id for routing/isolation.
   * </pre>
   *
   * <code>string tenant_id = 8;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * Tenant id for routing/isolation.
   * </pre>
   *
   * <code>string tenant_id = 8;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();
}
