// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * <pre>
 * ~200–500 ms of PCM16 mono &#64;16 kHz per message
 * </pre>
 *
 * Protobuf type {@code AudioChunk}
 */
@com.google.protobuf.Generated
public final class AudioChunk extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AudioChunk)
    AudioChunkOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "AudioChunk");
  }
  // Use AudioChunk.newBuilder() to construct.
  private AudioChunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AudioChunk() {
    sessionId_ = "";
    pcm16Le_ = com.google.protobuf.ByteString.EMPTY;
    lang_ = "";
    bffOriginUri_ = "";
    tenantId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_AudioChunk_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_AudioChunk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.AudioChunk.class, samuraibff.proto.AudioChunk.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQ_FIELD_NUMBER = 2;
  private long seq_ = 0L;
  /**
   * <pre>
   * incremental per session
   * </pre>
   *
   * <code>uint64 seq = 2;</code>
   * @return The seq.
   */
  @java.lang.Override
  public long getSeq() {
    return seq_;
  }

  public static final int T0_NS_FIELD_NUMBER = 3;
  private long t0Ns_ = 0L;
  /**
   * <pre>
   * producer monotonic timestamp OR sample time
   * </pre>
   *
   * <code>int64 t0_ns = 3;</code>
   * @return The t0Ns.
   */
  @java.lang.Override
  public long getT0Ns() {
    return t0Ns_;
  }

  public static final int SAMPLE_RATE_FIELD_NUMBER = 4;
  private int sampleRate_ = 0;
  /**
   * <pre>
   * 16000
   * </pre>
   *
   * <code>uint32 sample_rate = 4;</code>
   * @return The sampleRate.
   */
  @java.lang.Override
  public int getSampleRate() {
    return sampleRate_;
  }

  public static final int PCM16_LE_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString pcm16Le_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * little-endian PCM16 mono
   * </pre>
   *
   * <code>bytes pcm16_le = 5;</code>
   * @return The pcm16Le.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPcm16Le() {
    return pcm16Le_;
  }

  public static final int LANG_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lang_ = "";
  /**
   * <code>string lang = 6;</code>
   * @return The lang.
   */
  @java.lang.Override
  public java.lang.String getLang() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lang_ = s;
      return s;
    }
  }
  /**
   * <code>string lang = 6;</code>
   * @return The bytes for lang.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLangBytes() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BFF_ORIGIN_URI_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bffOriginUri_ = "";
  /**
   * <pre>
   * Base URI of the BFF instance that originated this session.
   * Used as a "reply-to" for refined events when Kafka partitions
   * distribute consumption across multiple BFF instances.
   * Example: "http://bff-1.internal:8000".
   * </pre>
   *
   * <code>string bff_origin_uri = 7;</code>
   * @return The bffOriginUri.
   */
  @java.lang.Override
  public java.lang.String getBffOriginUri() {
    java.lang.Object ref = bffOriginUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bffOriginUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Base URI of the BFF instance that originated this session.
   * Used as a "reply-to" for refined events when Kafka partitions
   * distribute consumption across multiple BFF instances.
   * Example: "http://bff-1.internal:8000".
   * </pre>
   *
   * <code>string bff_origin_uri = 7;</code>
   * @return The bytes for bffOriginUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBffOriginUriBytes() {
    java.lang.Object ref = bffOriginUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bffOriginUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * Tenant id for routing/isolation.
   * </pre>
   *
   * <code>string tenant_id = 8;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tenant id for routing/isolation.
   * </pre>
   *
   * <code>string tenant_id = 8;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (seq_ != 0L) {
      output.writeUInt64(2, seq_);
    }
    if (t0Ns_ != 0L) {
      output.writeInt64(3, t0Ns_);
    }
    if (sampleRate_ != 0) {
      output.writeUInt32(4, sampleRate_);
    }
    if (!pcm16Le_.isEmpty()) {
      output.writeBytes(5, pcm16Le_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, lang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bffOriginUri_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, bffOriginUri_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, tenantId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (seq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, seq_);
    }
    if (t0Ns_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, t0Ns_);
    }
    if (sampleRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, sampleRate_);
    }
    if (!pcm16Le_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, pcm16Le_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, lang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bffOriginUri_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, bffOriginUri_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, tenantId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.AudioChunk)) {
      return super.equals(obj);
    }
    samuraibff.proto.AudioChunk other = (samuraibff.proto.AudioChunk) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (getSeq()
        != other.getSeq()) return false;
    if (getT0Ns()
        != other.getT0Ns()) return false;
    if (getSampleRate()
        != other.getSampleRate()) return false;
    if (!getPcm16Le()
        .equals(other.getPcm16Le())) return false;
    if (!getLang()
        .equals(other.getLang())) return false;
    if (!getBffOriginUri()
        .equals(other.getBffOriginUri())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeq());
    hash = (37 * hash) + T0_NS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getT0Ns());
    hash = (37 * hash) + SAMPLE_RATE_FIELD_NUMBER;
    hash = (53 * hash) + getSampleRate();
    hash = (37 * hash) + PCM16_LE_FIELD_NUMBER;
    hash = (53 * hash) + getPcm16Le().hashCode();
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + getLang().hashCode();
    hash = (37 * hash) + BFF_ORIGIN_URI_FIELD_NUMBER;
    hash = (53 * hash) + getBffOriginUri().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.AudioChunk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AudioChunk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AudioChunk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AudioChunk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AudioChunk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.AudioChunk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.AudioChunk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.AudioChunk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.AudioChunk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.AudioChunk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.AudioChunk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.AudioChunk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.AudioChunk prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ~200–500 ms of PCM16 mono &#64;16 kHz per message
   * </pre>
   *
   * Protobuf type {@code AudioChunk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AudioChunk)
      samuraibff.proto.AudioChunkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_AudioChunk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_AudioChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.AudioChunk.class, samuraibff.proto.AudioChunk.Builder.class);
    }

    // Construct using samuraibff.proto.AudioChunk.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      seq_ = 0L;
      t0Ns_ = 0L;
      sampleRate_ = 0;
      pcm16Le_ = com.google.protobuf.ByteString.EMPTY;
      lang_ = "";
      bffOriginUri_ = "";
      tenantId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_AudioChunk_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.AudioChunk getDefaultInstanceForType() {
      return samuraibff.proto.AudioChunk.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.AudioChunk build() {
      samuraibff.proto.AudioChunk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.AudioChunk buildPartial() {
      samuraibff.proto.AudioChunk result = new samuraibff.proto.AudioChunk(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(samuraibff.proto.AudioChunk result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.seq_ = seq_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.t0Ns_ = t0Ns_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sampleRate_ = sampleRate_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.pcm16Le_ = pcm16Le_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lang_ = lang_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.bffOriginUri_ = bffOriginUri_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.tenantId_ = tenantId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.AudioChunk) {
        return mergeFrom((samuraibff.proto.AudioChunk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.AudioChunk other) {
      if (other == samuraibff.proto.AudioChunk.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSeq() != 0L) {
        setSeq(other.getSeq());
      }
      if (other.getT0Ns() != 0L) {
        setT0Ns(other.getT0Ns());
      }
      if (other.getSampleRate() != 0) {
        setSampleRate(other.getSampleRate());
      }
      if (!other.getPcm16Le().isEmpty()) {
        setPcm16Le(other.getPcm16Le());
      }
      if (!other.getLang().isEmpty()) {
        lang_ = other.lang_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getBffOriginUri().isEmpty()) {
        bffOriginUri_ = other.bffOriginUri_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              seq_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              t0Ns_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              sampleRate_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              pcm16Le_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              lang_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              bffOriginUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long seq_ ;
    /**
     * <pre>
     * incremental per session
     * </pre>
     *
     * <code>uint64 seq = 2;</code>
     * @return The seq.
     */
    @java.lang.Override
    public long getSeq() {
      return seq_;
    }
    /**
     * <pre>
     * incremental per session
     * </pre>
     *
     * <code>uint64 seq = 2;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(long value) {

      seq_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * incremental per session
     * </pre>
     *
     * <code>uint64 seq = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      bitField0_ = (bitField0_ & ~0x00000002);
      seq_ = 0L;
      onChanged();
      return this;
    }

    private long t0Ns_ ;
    /**
     * <pre>
     * producer monotonic timestamp OR sample time
     * </pre>
     *
     * <code>int64 t0_ns = 3;</code>
     * @return The t0Ns.
     */
    @java.lang.Override
    public long getT0Ns() {
      return t0Ns_;
    }
    /**
     * <pre>
     * producer monotonic timestamp OR sample time
     * </pre>
     *
     * <code>int64 t0_ns = 3;</code>
     * @param value The t0Ns to set.
     * @return This builder for chaining.
     */
    public Builder setT0Ns(long value) {

      t0Ns_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * producer monotonic timestamp OR sample time
     * </pre>
     *
     * <code>int64 t0_ns = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearT0Ns() {
      bitField0_ = (bitField0_ & ~0x00000004);
      t0Ns_ = 0L;
      onChanged();
      return this;
    }

    private int sampleRate_ ;
    /**
     * <pre>
     * 16000
     * </pre>
     *
     * <code>uint32 sample_rate = 4;</code>
     * @return The sampleRate.
     */
    @java.lang.Override
    public int getSampleRate() {
      return sampleRate_;
    }
    /**
     * <pre>
     * 16000
     * </pre>
     *
     * <code>uint32 sample_rate = 4;</code>
     * @param value The sampleRate to set.
     * @return This builder for chaining.
     */
    public Builder setSampleRate(int value) {

      sampleRate_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 16000
     * </pre>
     *
     * <code>uint32 sample_rate = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleRate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sampleRate_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString pcm16Le_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * little-endian PCM16 mono
     * </pre>
     *
     * <code>bytes pcm16_le = 5;</code>
     * @return The pcm16Le.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPcm16Le() {
      return pcm16Le_;
    }
    /**
     * <pre>
     * little-endian PCM16 mono
     * </pre>
     *
     * <code>bytes pcm16_le = 5;</code>
     * @param value The pcm16Le to set.
     * @return This builder for chaining.
     */
    public Builder setPcm16Le(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      pcm16Le_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * little-endian PCM16 mono
     * </pre>
     *
     * <code>bytes pcm16_le = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPcm16Le() {
      bitField0_ = (bitField0_ & ~0x00000010);
      pcm16Le_ = getDefaultInstance().getPcm16Le();
      onChanged();
      return this;
    }

    private java.lang.Object lang_ = "";
    /**
     * <code>string lang = 6;</code>
     * @return The lang.
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lang = 6;</code>
     * @return The bytes for lang.
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lang = 6;</code>
     * @param value The lang to set.
     * @return This builder for chaining.
     */
    public Builder setLang(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lang_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLang() {
      lang_ = getDefaultInstance().getLang();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 6;</code>
     * @param value The bytes for lang to set.
     * @return This builder for chaining.
     */
    public Builder setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lang_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object bffOriginUri_ = "";
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * Used as a "reply-to" for refined events when Kafka partitions
     * distribute consumption across multiple BFF instances.
     * Example: "http://bff-1.internal:8000".
     * </pre>
     *
     * <code>string bff_origin_uri = 7;</code>
     * @return The bffOriginUri.
     */
    public java.lang.String getBffOriginUri() {
      java.lang.Object ref = bffOriginUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bffOriginUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * Used as a "reply-to" for refined events when Kafka partitions
     * distribute consumption across multiple BFF instances.
     * Example: "http://bff-1.internal:8000".
     * </pre>
     *
     * <code>string bff_origin_uri = 7;</code>
     * @return The bytes for bffOriginUri.
     */
    public com.google.protobuf.ByteString
        getBffOriginUriBytes() {
      java.lang.Object ref = bffOriginUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bffOriginUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * Used as a "reply-to" for refined events when Kafka partitions
     * distribute consumption across multiple BFF instances.
     * Example: "http://bff-1.internal:8000".
     * </pre>
     *
     * <code>string bff_origin_uri = 7;</code>
     * @param value The bffOriginUri to set.
     * @return This builder for chaining.
     */
    public Builder setBffOriginUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bffOriginUri_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * Used as a "reply-to" for refined events when Kafka partitions
     * distribute consumption across multiple BFF instances.
     * Example: "http://bff-1.internal:8000".
     * </pre>
     *
     * <code>string bff_origin_uri = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBffOriginUri() {
      bffOriginUri_ = getDefaultInstance().getBffOriginUri();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * Used as a "reply-to" for refined events when Kafka partitions
     * distribute consumption across multiple BFF instances.
     * Example: "http://bff-1.internal:8000".
     * </pre>
     *
     * <code>string bff_origin_uri = 7;</code>
     * @param value The bytes for bffOriginUri to set.
     * @return This builder for chaining.
     */
    public Builder setBffOriginUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bffOriginUri_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * </pre>
     *
     * <code>string tenant_id = 8;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * </pre>
     *
     * <code>string tenant_id = 8;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * </pre>
     *
     * <code>string tenant_id = 8;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * </pre>
     *
     * <code>string tenant_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * </pre>
     *
     * <code>string tenant_id = 8;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AudioChunk)
  }

  // @@protoc_insertion_point(class_scope:AudioChunk)
  private static final samuraibff.proto.AudioChunk DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.AudioChunk();
  }

  public static samuraibff.proto.AudioChunk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AudioChunk>
      PARSER = new com.google.protobuf.AbstractParser<AudioChunk>() {
    @java.lang.Override
    public AudioChunk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AudioChunk> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AudioChunk> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.AudioChunk getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

