// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface AudioArtifactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AudioArtifact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string artifact_id = 1 [json_name = "artifactId"];</code>
   * @return The artifactId.
   */
  java.lang.String getArtifactId();
  /**
   * <code>string artifact_id = 1 [json_name = "artifactId"];</code>
   * @return The bytes for artifactId.
   */
  com.google.protobuf.ByteString
      getArtifactIdBytes();

  /**
   * <code>string storage_uri = 2 [json_name = "storageUri"];</code>
   * @return The storageUri.
   */
  java.lang.String getStorageUri();
  /**
   * <code>string storage_uri = 2 [json_name = "storageUri"];</code>
   * @return The bytes for storageUri.
   */
  com.google.protobuf.ByteString
      getStorageUriBytes();

  /**
   * <code>string sha256 = 3 [json_name = "sha256"];</code>
   * @return The sha256.
   */
  java.lang.String getSha256();
  /**
   * <code>string sha256 = 3 [json_name = "sha256"];</code>
   * @return The bytes for sha256.
   */
  com.google.protobuf.ByteString
      getSha256Bytes();

  /**
   * <code>uint64 size_bytes = 4 [json_name = "sizeBytes"];</code>
   * @return The sizeBytes.
   */
  long getSizeBytes();

  /**
   * <code>uint32 sample_rate = 5 [json_name = "sampleRate"];</code>
   * @return The sampleRate.
   */
  int getSampleRate();

  /**
   * <code>uint64 sample_count = 6 [json_name = "sampleCount"];</code>
   * @return The sampleCount.
   */
  long getSampleCount();

  /**
   * <code>string media_type = 7 [json_name = "mediaType"];</code>
   * @return The mediaType.
   */
  java.lang.String getMediaType();
  /**
   * <code>string media_type = 7 [json_name = "mediaType"];</code>
   * @return The bytes for mediaType.
   */
  com.google.protobuf.ByteString
      getMediaTypeBytes();

  /**
   * <code>string version_id = 8 [json_name = "versionId"];</code>
   * @return The versionId.
   */
  java.lang.String getVersionId();
  /**
   * <code>string version_id = 8 [json_name = "versionId"];</code>
   * @return The bytes for versionId.
   */
  com.google.protobuf.ByteString
      getVersionIdBytes();
}
