// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * Protobuf type {@code DiarEvent}
 */
@com.google.protobuf.Generated
public final class DiarEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:DiarEvent)
    DiarEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "DiarEvent");
  }
  // Use DiarEvent.newBuilder() to construct.
  private DiarEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DiarEvent() {
    sessionId_ = "";
    speaker_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_DiarEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_DiarEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.DiarEvent.class, samuraibff.proto.DiarEvent.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_S_FIELD_NUMBER = 2;
  private double startS_ = 0D;
  /**
   * <code>double start_s = 2;</code>
   * @return The startS.
   */
  @java.lang.Override
  public double getStartS() {
    return startS_;
  }

  public static final int END_S_FIELD_NUMBER = 3;
  private double endS_ = 0D;
  /**
   * <code>double end_s = 3;</code>
   * @return The endS.
   */
  @java.lang.Override
  public double getEndS() {
    return endS_;
  }

  public static final int SPEAKER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object speaker_ = "";
  /**
   * <pre>
   * "SPEAKER_00" or enrolled name
   * </pre>
   *
   * <code>string speaker = 4;</code>
   * @return The speaker.
   */
  @java.lang.Override
  public java.lang.String getSpeaker() {
    java.lang.Object ref = speaker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      speaker_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "SPEAKER_00" or enrolled name
   * </pre>
   *
   * <code>string speaker = 4;</code>
   * @return The bytes for speaker.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpeakerBytes() {
    java.lang.Object ref = speaker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      speaker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 5;
  private float confidence_ = 0F;
  /**
   * <pre>
   * 0..1
   * </pre>
   *
   * <code>float confidence = 5;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public float getConfidence() {
    return confidence_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (java.lang.Double.doubleToRawLongBits(startS_) != 0) {
      output.writeDouble(2, startS_);
    }
    if (java.lang.Double.doubleToRawLongBits(endS_) != 0) {
      output.writeDouble(3, endS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(speaker_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, speaker_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      output.writeFloat(5, confidence_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (java.lang.Double.doubleToRawLongBits(startS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, startS_);
    }
    if (java.lang.Double.doubleToRawLongBits(endS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, endS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(speaker_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, speaker_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, confidence_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.DiarEvent)) {
      return super.equals(obj);
    }
    samuraibff.proto.DiarEvent other = (samuraibff.proto.DiarEvent) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (java.lang.Double.doubleToLongBits(getStartS())
        != java.lang.Double.doubleToLongBits(
            other.getStartS())) return false;
    if (java.lang.Double.doubleToLongBits(getEndS())
        != java.lang.Double.doubleToLongBits(
            other.getEndS())) return false;
    if (!getSpeaker()
        .equals(other.getSpeaker())) return false;
    if (java.lang.Float.floatToIntBits(getConfidence())
        != java.lang.Float.floatToIntBits(
            other.getConfidence())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + START_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getStartS()));
    hash = (37 * hash) + END_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEndS()));
    hash = (37 * hash) + SPEAKER_FIELD_NUMBER;
    hash = (53 * hash) + getSpeaker().hashCode();
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfidence());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.DiarEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.DiarEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.DiarEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.DiarEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.DiarEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.DiarEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.DiarEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.DiarEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.DiarEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.DiarEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.DiarEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.DiarEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.DiarEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DiarEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DiarEvent)
      samuraibff.proto.DiarEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_DiarEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_DiarEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.DiarEvent.class, samuraibff.proto.DiarEvent.Builder.class);
    }

    // Construct using samuraibff.proto.DiarEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      startS_ = 0D;
      endS_ = 0D;
      speaker_ = "";
      confidence_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_DiarEvent_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.DiarEvent getDefaultInstanceForType() {
      return samuraibff.proto.DiarEvent.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.DiarEvent build() {
      samuraibff.proto.DiarEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.DiarEvent buildPartial() {
      samuraibff.proto.DiarEvent result = new samuraibff.proto.DiarEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(samuraibff.proto.DiarEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.startS_ = startS_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endS_ = endS_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.speaker_ = speaker_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.confidence_ = confidence_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.DiarEvent) {
        return mergeFrom((samuraibff.proto.DiarEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.DiarEvent other) {
      if (other == samuraibff.proto.DiarEvent.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getStartS()) != 0) {
        setStartS(other.getStartS());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getEndS()) != 0) {
        setEndS(other.getEndS());
      }
      if (!other.getSpeaker().isEmpty()) {
        speaker_ = other.speaker_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (java.lang.Float.floatToRawIntBits(other.getConfidence()) != 0) {
        setConfidence(other.getConfidence());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              startS_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              endS_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              speaker_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 45: {
              confidence_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double startS_ ;
    /**
     * <code>double start_s = 2;</code>
     * @return The startS.
     */
    @java.lang.Override
    public double getStartS() {
      return startS_;
    }
    /**
     * <code>double start_s = 2;</code>
     * @param value The startS to set.
     * @return This builder for chaining.
     */
    public Builder setStartS(double value) {

      startS_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double start_s = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartS() {
      bitField0_ = (bitField0_ & ~0x00000002);
      startS_ = 0D;
      onChanged();
      return this;
    }

    private double endS_ ;
    /**
     * <code>double end_s = 3;</code>
     * @return The endS.
     */
    @java.lang.Override
    public double getEndS() {
      return endS_;
    }
    /**
     * <code>double end_s = 3;</code>
     * @param value The endS to set.
     * @return This builder for chaining.
     */
    public Builder setEndS(double value) {

      endS_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double end_s = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndS() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endS_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object speaker_ = "";
    /**
     * <pre>
     * "SPEAKER_00" or enrolled name
     * </pre>
     *
     * <code>string speaker = 4;</code>
     * @return The speaker.
     */
    public java.lang.String getSpeaker() {
      java.lang.Object ref = speaker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        speaker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "SPEAKER_00" or enrolled name
     * </pre>
     *
     * <code>string speaker = 4;</code>
     * @return The bytes for speaker.
     */
    public com.google.protobuf.ByteString
        getSpeakerBytes() {
      java.lang.Object ref = speaker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        speaker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "SPEAKER_00" or enrolled name
     * </pre>
     *
     * <code>string speaker = 4;</code>
     * @param value The speaker to set.
     * @return This builder for chaining.
     */
    public Builder setSpeaker(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      speaker_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "SPEAKER_00" or enrolled name
     * </pre>
     *
     * <code>string speaker = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeaker() {
      speaker_ = getDefaultInstance().getSpeaker();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "SPEAKER_00" or enrolled name
     * </pre>
     *
     * <code>string speaker = 4;</code>
     * @param value The bytes for speaker to set.
     * @return This builder for chaining.
     */
    public Builder setSpeakerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      speaker_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private float confidence_ ;
    /**
     * <pre>
     * 0..1
     * </pre>
     *
     * <code>float confidence = 5;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }
    /**
     * <pre>
     * 0..1
     * </pre>
     *
     * <code>float confidence = 5;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {

      confidence_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0..1
     * </pre>
     *
     * <code>float confidence = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      bitField0_ = (bitField0_ & ~0x00000010);
      confidence_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:DiarEvent)
  }

  // @@protoc_insertion_point(class_scope:DiarEvent)
  private static final samuraibff.proto.DiarEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.DiarEvent();
  }

  public static samuraibff.proto.DiarEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DiarEvent>
      PARSER = new com.google.protobuf.AbstractParser<DiarEvent>() {
    @java.lang.Override
    public DiarEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DiarEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DiarEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.DiarEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

