// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface DiarEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DiarEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>double start_s = 2 [json_name = "startS"];</code>
   * @return The startS.
   */
  double getStartS();

  /**
   * <code>double end_s = 3 [json_name = "endS"];</code>
   * @return The endS.
   */
  double getEndS();

  /**
   * <pre>
   * "SPEAKER_00" or enrolled name
   * </pre>
   *
   * <code>string speaker = 4 [json_name = "speaker"];</code>
   * @return The speaker.
   */
  java.lang.String getSpeaker();
  /**
   * <pre>
   * "SPEAKER_00" or enrolled name
   * </pre>
   *
   * <code>string speaker = 4 [json_name = "speaker"];</code>
   * @return The bytes for speaker.
   */
  com.google.protobuf.ByteString
      getSpeakerBytes();

  /**
   * <pre>
   * 0..1
   * </pre>
   *
   * <code>float confidence = 5 [json_name = "confidence"];</code>
   * @return The confidence.
   */
  float getConfidence();
}
