// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface FinalTrackResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FinalTrackResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 schema_version = 1 [json_name = "schemaVersion"];</code>
   * @return The schemaVersion.
   */
  int getSchemaVersion();

  /**
   * <code>string session_id = 2 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 2 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string stage = 4 [json_name = "stage"];</code>
   * @return The stage.
   */
  java.lang.String getStage();
  /**
   * <code>string stage = 4 [json_name = "stage"];</code>
   * @return The bytes for stage.
   */
  com.google.protobuf.ByteString
      getStageBytes();

  /**
   * <code>string track_id = 5 [json_name = "trackId"];</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <code>string track_id = 5 [json_name = "trackId"];</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <code>string profile_id = 6 [json_name = "profileId"];</code>
   * @return The profileId.
   */
  java.lang.String getProfileId();
  /**
   * <code>string profile_id = 6 [json_name = "profileId"];</code>
   * @return The bytes for profileId.
   */
  com.google.protobuf.ByteString
      getProfileIdBytes();

  /**
   * <code>string run_id = 7 [json_name = "runId"];</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 7 [json_name = "runId"];</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>string attempt_id = 8 [json_name = "attemptId"];</code>
   * @return The attemptId.
   */
  java.lang.String getAttemptId();
  /**
   * <code>string attempt_id = 8 [json_name = "attemptId"];</code>
   * @return The bytes for attemptId.
   */
  com.google.protobuf.ByteString
      getAttemptIdBytes();

  /**
   * <code>string result_id = 9 [json_name = "resultId"];</code>
   * @return The resultId.
   */
  java.lang.String getResultId();
  /**
   * <code>string result_id = 9 [json_name = "resultId"];</code>
   * @return The bytes for resultId.
   */
  com.google.protobuf.ByteString
      getResultIdBytes();

  /**
   * <code>string unit_id = 10 [json_name = "unitId"];</code>
   * @return The unitId.
   */
  java.lang.String getUnitId();
  /**
   * <code>string unit_id = 10 [json_name = "unitId"];</code>
   * @return The bytes for unitId.
   */
  com.google.protobuf.ByteString
      getUnitIdBytes();

  /**
   * <code>uint32 revision = 11 [json_name = "revision"];</code>
   * @return The revision.
   */
  int getRevision();

  /**
   * <code>string status = 12 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 12 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>.AudioArtifact source = 13 [json_name = "source"];</code>
   * @return Whether the source field is set.
   */
  boolean hasSource();
  /**
   * <code>.AudioArtifact source = 13 [json_name = "source"];</code>
   * @return The source.
   */
  samuraibff.proto.AudioArtifact getSource();
  /**
   * <code>.AudioArtifact source = 13 [json_name = "source"];</code>
   */
  samuraibff.proto.AudioArtifactOrBuilder getSourceOrBuilder();

  /**
   * <code>string result_uri = 14 [json_name = "resultUri"];</code>
   * @return The resultUri.
   */
  java.lang.String getResultUri();
  /**
   * <code>string result_uri = 14 [json_name = "resultUri"];</code>
   * @return The bytes for resultUri.
   */
  com.google.protobuf.ByteString
      getResultUriBytes();

  /**
   * <code>string result_sha256 = 15 [json_name = "resultSha256"];</code>
   * @return The resultSha256.
   */
  java.lang.String getResultSha256();
  /**
   * <code>string result_sha256 = 15 [json_name = "resultSha256"];</code>
   * @return The bytes for resultSha256.
   */
  com.google.protobuf.ByteString
      getResultSha256Bytes();

  /**
   * <code>bool primary = 16 [json_name = "primary"];</code>
   * @return The primary.
   */
  boolean getPrimary();

  /**
   * <code>string error_code = 17 [json_name = "errorCode"];</code>
   * @return The errorCode.
   */
  java.lang.String getErrorCode();
  /**
   * <code>string error_code = 17 [json_name = "errorCode"];</code>
   * @return The bytes for errorCode.
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @return A list containing the degradations.
   */
  java.util.List<java.lang.String>
      getDegradationsList();
  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @return The count of degradations.
   */
  int getDegradationsCount();
  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @param index The index of the element to return.
   * @return The degradations at the given index.
   */
  java.lang.String getDegradations(int index);
  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the degradations at the given index.
   */
  com.google.protobuf.ByteString
      getDegradationsBytes(int index);

  /**
   * <code>bool segment_timestamps = 19 [json_name = "segmentTimestamps"];</code>
   * @return The segmentTimestamps.
   */
  boolean getSegmentTimestamps();

  /**
   * <code>bool word_timestamps = 20 [json_name = "wordTimestamps"];</code>
   * @return The wordTimestamps.
   */
  boolean getWordTimestamps();

  /**
   * <code>bool speaker_labels = 21 [json_name = "speakerLabels"];</code>
   * @return The speakerLabels.
   */
  boolean getSpeakerLabels();

  /**
   * <code>string provenance_json = 22 [json_name = "provenanceJson"];</code>
   * @return The provenanceJson.
   */
  java.lang.String getProvenanceJson();
  /**
   * <code>string provenance_json = 22 [json_name = "provenanceJson"];</code>
   * @return The bytes for provenanceJson.
   */
  com.google.protobuf.ByteString
      getProvenanceJsonBytes();

  /**
   * <code>int64 created_at_ns = 23 [json_name = "createdAtNs"];</code>
   * @return The createdAtNs.
   */
  long getCreatedAtNs();

  /**
   * <code>string lang = 24 [json_name = "lang"];</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 24 [json_name = "lang"];</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>string plan_id = 25 [json_name = "planId"];</code>
   * @return The planId.
   */
  java.lang.String getPlanId();
  /**
   * <code>string plan_id = 25 [json_name = "planId"];</code>
   * @return The bytes for planId.
   */
  com.google.protobuf.ByteString
      getPlanIdBytes();
}
