// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface FinalEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FinalEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>double start_s = 2;</code>
   * @return The startS.
   */
  double getStartS();

  /**
   * <code>double end_s = 3;</code>
   * @return The endS.
   */
  double getEndS();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string speaker = 5;</code>
   * @return The speaker.
   */
  java.lang.String getSpeaker();
  /**
   * <code>string speaker = 5;</code>
   * @return The bytes for speaker.
   */
  com.google.protobuf.ByteString
      getSpeakerBytes();

  /**
   * <code>string lang = 6;</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 6;</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>repeated .WordAlignment words = 7;</code>
   */
  java.util.List<samuraibff.proto.WordAlignment> 
      getWordsList();
  /**
   * <code>repeated .WordAlignment words = 7;</code>
   */
  samuraibff.proto.WordAlignment getWords(int index);
  /**
   * <code>repeated .WordAlignment words = 7;</code>
   */
  int getWordsCount();
  /**
   * <code>repeated .WordAlignment words = 7;</code>
   */
  java.util.List<? extends samuraibff.proto.WordAlignmentOrBuilder> 
      getWordsOrBuilderList();
  /**
   * <code>repeated .WordAlignment words = 7;</code>
   */
  samuraibff.proto.WordAlignmentOrBuilder getWordsOrBuilder(
      int index);
}
