// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface FinalTrackResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FinalTrackResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 schema_version = 1 [json_name = "schemaVersion"];</code>
   * @return The schemaVersion.
   */
  int getSchemaVersion();

  /**
   * <code>string session_id = 2 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 2 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 3 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string track_id = 5 [json_name = "trackId"];</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <code>string track_id = 5 [json_name = "trackId"];</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();

  /**
   * <code>string profile_id = 6 [json_name = "profileId"];</code>
   * @return The profileId.
   */
  java.lang.String getProfileId();
  /**
   * <code>string profile_id = 6 [json_name = "profileId"];</code>
   * @return The bytes for profileId.
   */
  com.google.protobuf.ByteString
      getProfileIdBytes();

  /**
   * <code>string result_id = 9 [json_name = "resultId"];</code>
   * @return The resultId.
   */
  java.lang.String getResultId();
  /**
   * <code>string result_id = 9 [json_name = "resultId"];</code>
   * @return The bytes for resultId.
   */
  com.google.protobuf.ByteString
      getResultIdBytes();

  /**
   * <code>string status = 12 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 12 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>.AudioArtifact source = 13 [json_name = "source"];</code>
   * @return Whether the source field is set.
   */
  boolean hasSource();
  /**
   * <code>.AudioArtifact source = 13 [json_name = "source"];</code>
   * @return The source.
   */
  samuraibff.proto.AudioArtifact getSource();
  /**
   * <code>.AudioArtifact source = 13 [json_name = "source"];</code>
   */
  samuraibff.proto.AudioArtifactOrBuilder getSourceOrBuilder();

  /**
   * <code>string error_code = 17 [json_name = "errorCode"];</code>
   * @return The errorCode.
   */
  java.lang.String getErrorCode();
  /**
   * <code>string error_code = 17 [json_name = "errorCode"];</code>
   * @return The bytes for errorCode.
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @return A list containing the degradations.
   */
  java.util.List<java.lang.String>
      getDegradationsList();
  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @return The count of degradations.
   */
  int getDegradationsCount();
  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @param index The index of the element to return.
   * @return The degradations at the given index.
   */
  java.lang.String getDegradations(int index);
  /**
   * <code>repeated string degradations = 18 [json_name = "degradations"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the degradations at the given index.
   */
  com.google.protobuf.ByteString
      getDegradationsBytes(int index);

  /**
   * <code>bool segment_timestamps = 19 [json_name = "segmentTimestamps"];</code>
   * @return The segmentTimestamps.
   */
  boolean getSegmentTimestamps();

  /**
   * <code>bool word_timestamps = 20 [json_name = "wordTimestamps"];</code>
   * @return The wordTimestamps.
   */
  boolean getWordTimestamps();

  /**
   * <code>bool speaker_labels = 21 [json_name = "speakerLabels"];</code>
   * @return The speakerLabels.
   */
  boolean getSpeakerLabels();

  /**
   * <code>int64 created_at_ns = 23 [json_name = "createdAtNs"];</code>
   * @return The createdAtNs.
   */
  long getCreatedAtNs();

  /**
   * <code>string lang = 24 [json_name = "lang"];</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 24 [json_name = "lang"];</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>string plan_id = 25 [json_name = "planId"];</code>
   * @return The planId.
   */
  java.lang.String getPlanId();
  /**
   * <code>string plan_id = 25 [json_name = "planId"];</code>
   * @return The bytes for planId.
   */
  com.google.protobuf.ByteString
      getPlanIdBytes();

  /**
   * <pre>
   * Tag 26 belongs to refinement_window in the preserved refinement draft.
   * </pre>
   *
   * <code>string full_text = 27 [json_name = "fullText"];</code>
   * @return The fullText.
   */
  java.lang.String getFullText();
  /**
   * <pre>
   * Tag 26 belongs to refinement_window in the preserved refinement draft.
   * </pre>
   *
   * <code>string full_text = 27 [json_name = "fullText"];</code>
   * @return The bytes for fullText.
   */
  com.google.protobuf.ByteString
      getFullTextBytes();

  /**
   * <code>repeated .SessionTranscriptSegment segments = 28 [json_name = "segments"];</code>
   */
  java.util.List<samuraibff.proto.SessionTranscriptSegment> 
      getSegmentsList();
  /**
   * <code>repeated .SessionTranscriptSegment segments = 28 [json_name = "segments"];</code>
   */
  samuraibff.proto.SessionTranscriptSegment getSegments(int index);
  /**
   * <code>repeated .SessionTranscriptSegment segments = 28 [json_name = "segments"];</code>
   */
  int getSegmentsCount();
  /**
   * <code>repeated .SessionTranscriptSegment segments = 28 [json_name = "segments"];</code>
   */
  java.util.List<? extends samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
      getSegmentsOrBuilderList();
  /**
   * <code>repeated .SessionTranscriptSegment segments = 28 [json_name = "segments"];</code>
   */
  samuraibff.proto.SessionTranscriptSegmentOrBuilder getSegmentsOrBuilder(
      int index);
}
