// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface RealtimeCapabilitiesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RealtimeCapabilitiesRequest)
    com.google.protobuf.MessageOrBuilder {
}
