// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface RecordingFinishedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingFinished)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * e.g. file://..., s3://...
   * </pre>
   *
   * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
   * @return The recordingUrl.
   */
  java.lang.String getRecordingUrl();
  /**
   * <pre>
   * e.g. file://..., s3://...
   * </pre>
   *
   * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
   * @return The bytes for recordingUrl.
   */
  com.google.protobuf.ByteString
      getRecordingUrlBytes();

  /**
   * <code>double duration_s = 3 [json_name = "durationS"];</code>
   * @return The durationS.
   */
  double getDurationS();

  /**
   * <code>int32 sample_rate = 4 [json_name = "sampleRate"];</code>
   * @return The sampleRate.
   */
  int getSampleRate();

  /**
   * <code>string lang = 5 [json_name = "lang"];</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 5 [json_name = "lang"];</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <pre>
   * optional tenant/client label for downstream routing
   * </pre>
   *
   * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * optional tenant/client label for downstream routing
   * </pre>
   *
   * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   * when this event was created
   * </pre>
   *
   * <code>int64 created_at_ns = 7 [json_name = "createdAtNs"];</code>
   * @return The createdAtNs.
   */
  long getCreatedAtNs();

  /**
   * <pre>
   * Additive final-track contract. Absent on legacy recordings.
   * </pre>
   *
   * <code>.AudioArtifact source = 8 [json_name = "source"];</code>
   * @return Whether the source field is set.
   */
  boolean hasSource();
  /**
   * <pre>
   * Additive final-track contract. Absent on legacy recordings.
   * </pre>
   *
   * <code>.AudioArtifact source = 8 [json_name = "source"];</code>
   * @return The source.
   */
  samuraibff.proto.AudioArtifact getSource();
  /**
   * <pre>
   * Additive final-track contract. Absent on legacy recordings.
   * </pre>
   *
   * <code>.AudioArtifact source = 8 [json_name = "source"];</code>
   */
  samuraibff.proto.AudioArtifactOrBuilder getSourceOrBuilder();

  /**
   * <code>.AsyncTrackPlan final_plan = 9 [json_name = "finalPlan"];</code>
   * @return Whether the finalPlan field is set.
   */
  boolean hasFinalPlan();
  /**
   * <code>.AsyncTrackPlan final_plan = 9 [json_name = "finalPlan"];</code>
   * @return The finalPlan.
   */
  samuraibff.proto.AsyncTrackPlan getFinalPlan();
  /**
   * <code>.AsyncTrackPlan final_plan = 9 [json_name = "finalPlan"];</code>
   */
  samuraibff.proto.AsyncTrackPlanOrBuilder getFinalPlanOrBuilder();
}
