// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * <pre>
 * Recording-level metadata: “recording finished, file is available”
 * </pre>
 *
 * Protobuf type {@code RecordingFinished}
 */
@com.google.protobuf.Generated
public final class RecordingFinished extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RecordingFinished)
    RecordingFinishedOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "RecordingFinished");
  }
  // Use RecordingFinished.newBuilder() to construct.
  private RecordingFinished(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RecordingFinished() {
    sessionId_ = "";
    recordingUrl_ = "";
    lang_ = "";
    tenantId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_RecordingFinished_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_RecordingFinished_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.RecordingFinished.class, samuraibff.proto.RecordingFinished.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDING_URL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recordingUrl_ = "";
  /**
   * <pre>
   * e.g. file://..., s3://...
   * </pre>
   *
   * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
   * @return The recordingUrl.
   */
  @java.lang.Override
  public java.lang.String getRecordingUrl() {
    java.lang.Object ref = recordingUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordingUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g. file://..., s3://...
   * </pre>
   *
   * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
   * @return The bytes for recordingUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecordingUrlBytes() {
    java.lang.Object ref = recordingUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordingUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_S_FIELD_NUMBER = 3;
  private double durationS_ = 0D;
  /**
   * <code>double duration_s = 3 [json_name = "durationS"];</code>
   * @return The durationS.
   */
  @java.lang.Override
  public double getDurationS() {
    return durationS_;
  }

  public static final int SAMPLE_RATE_FIELD_NUMBER = 4;
  private int sampleRate_ = 0;
  /**
   * <code>int32 sample_rate = 4 [json_name = "sampleRate"];</code>
   * @return The sampleRate.
   */
  @java.lang.Override
  public int getSampleRate() {
    return sampleRate_;
  }

  public static final int LANG_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lang_ = "";
  /**
   * <code>string lang = 5 [json_name = "lang"];</code>
   * @return The lang.
   */
  @java.lang.Override
  public java.lang.String getLang() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lang_ = s;
      return s;
    }
  }
  /**
   * <code>string lang = 5 [json_name = "lang"];</code>
   * @return The bytes for lang.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLangBytes() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * optional tenant/client label for downstream routing
   * </pre>
   *
   * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional tenant/client label for downstream routing
   * </pre>
   *
   * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_NS_FIELD_NUMBER = 7;
  private long createdAtNs_ = 0L;
  /**
   * <pre>
   * when this event was created
   * </pre>
   *
   * <code>int64 created_at_ns = 7 [json_name = "createdAtNs"];</code>
   * @return The createdAtNs.
   */
  @java.lang.Override
  public long getCreatedAtNs() {
    return createdAtNs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recordingUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, recordingUrl_);
    }
    if (java.lang.Double.doubleToRawLongBits(durationS_) != 0) {
      output.writeDouble(3, durationS_);
    }
    if (sampleRate_ != 0) {
      output.writeInt32(4, sampleRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, lang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, tenantId_);
    }
    if (createdAtNs_ != 0L) {
      output.writeInt64(7, createdAtNs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recordingUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, recordingUrl_);
    }
    if (java.lang.Double.doubleToRawLongBits(durationS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, durationS_);
    }
    if (sampleRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, sampleRate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, lang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, tenantId_);
    }
    if (createdAtNs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, createdAtNs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.RecordingFinished)) {
      return super.equals(obj);
    }
    samuraibff.proto.RecordingFinished other = (samuraibff.proto.RecordingFinished) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getRecordingUrl()
        .equals(other.getRecordingUrl())) return false;
    if (java.lang.Double.doubleToLongBits(getDurationS())
        != java.lang.Double.doubleToLongBits(
            other.getDurationS())) return false;
    if (getSampleRate()
        != other.getSampleRate()) return false;
    if (!getLang()
        .equals(other.getLang())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (getCreatedAtNs()
        != other.getCreatedAtNs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + RECORDING_URL_FIELD_NUMBER;
    hash = (53 * hash) + getRecordingUrl().hashCode();
    hash = (37 * hash) + DURATION_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDurationS()));
    hash = (37 * hash) + SAMPLE_RATE_FIELD_NUMBER;
    hash = (53 * hash) + getSampleRate();
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + getLang().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + CREATED_AT_NS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAtNs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.RecordingFinished parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.RecordingFinished parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.RecordingFinished parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.RecordingFinished parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.RecordingFinished prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Recording-level metadata: “recording finished, file is available”
   * </pre>
   *
   * Protobuf type {@code RecordingFinished}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RecordingFinished)
      samuraibff.proto.RecordingFinishedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_RecordingFinished_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_RecordingFinished_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.RecordingFinished.class, samuraibff.proto.RecordingFinished.Builder.class);
    }

    // Construct using samuraibff.proto.RecordingFinished.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      recordingUrl_ = "";
      durationS_ = 0D;
      sampleRate_ = 0;
      lang_ = "";
      tenantId_ = "";
      createdAtNs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_RecordingFinished_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.RecordingFinished getDefaultInstanceForType() {
      return samuraibff.proto.RecordingFinished.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.RecordingFinished build() {
      samuraibff.proto.RecordingFinished result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.RecordingFinished buildPartial() {
      samuraibff.proto.RecordingFinished result = new samuraibff.proto.RecordingFinished(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(samuraibff.proto.RecordingFinished result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.recordingUrl_ = recordingUrl_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.durationS_ = durationS_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sampleRate_ = sampleRate_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lang_ = lang_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.createdAtNs_ = createdAtNs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.RecordingFinished) {
        return mergeFrom((samuraibff.proto.RecordingFinished)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.RecordingFinished other) {
      if (other == samuraibff.proto.RecordingFinished.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRecordingUrl().isEmpty()) {
        recordingUrl_ = other.recordingUrl_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getDurationS()) != 0) {
        setDurationS(other.getDurationS());
      }
      if (other.getSampleRate() != 0) {
        setSampleRate(other.getSampleRate());
      }
      if (!other.getLang().isEmpty()) {
        lang_ = other.lang_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getCreatedAtNs() != 0L) {
        setCreatedAtNs(other.getCreatedAtNs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              recordingUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              durationS_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 32: {
              sampleRate_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              lang_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              createdAtNs_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object recordingUrl_ = "";
    /**
     * <pre>
     * e.g. file://..., s3://...
     * </pre>
     *
     * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
     * @return The recordingUrl.
     */
    public java.lang.String getRecordingUrl() {
      java.lang.Object ref = recordingUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordingUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. file://..., s3://...
     * </pre>
     *
     * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
     * @return The bytes for recordingUrl.
     */
    public com.google.protobuf.ByteString
        getRecordingUrlBytes() {
      java.lang.Object ref = recordingUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordingUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. file://..., s3://...
     * </pre>
     *
     * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
     * @param value The recordingUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRecordingUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recordingUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. file://..., s3://...
     * </pre>
     *
     * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordingUrl() {
      recordingUrl_ = getDefaultInstance().getRecordingUrl();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. file://..., s3://...
     * </pre>
     *
     * <code>string recording_url = 2 [json_name = "recordingUrl"];</code>
     * @param value The bytes for recordingUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRecordingUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recordingUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double durationS_ ;
    /**
     * <code>double duration_s = 3 [json_name = "durationS"];</code>
     * @return The durationS.
     */
    @java.lang.Override
    public double getDurationS() {
      return durationS_;
    }
    /**
     * <code>double duration_s = 3 [json_name = "durationS"];</code>
     * @param value The durationS to set.
     * @return This builder for chaining.
     */
    public Builder setDurationS(double value) {

      durationS_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double duration_s = 3 [json_name = "durationS"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationS() {
      bitField0_ = (bitField0_ & ~0x00000004);
      durationS_ = 0D;
      onChanged();
      return this;
    }

    private int sampleRate_ ;
    /**
     * <code>int32 sample_rate = 4 [json_name = "sampleRate"];</code>
     * @return The sampleRate.
     */
    @java.lang.Override
    public int getSampleRate() {
      return sampleRate_;
    }
    /**
     * <code>int32 sample_rate = 4 [json_name = "sampleRate"];</code>
     * @param value The sampleRate to set.
     * @return This builder for chaining.
     */
    public Builder setSampleRate(int value) {

      sampleRate_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sample_rate = 4 [json_name = "sampleRate"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleRate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sampleRate_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object lang_ = "";
    /**
     * <code>string lang = 5 [json_name = "lang"];</code>
     * @return The lang.
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lang = 5 [json_name = "lang"];</code>
     * @return The bytes for lang.
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lang = 5 [json_name = "lang"];</code>
     * @param value The lang to set.
     * @return This builder for chaining.
     */
    public Builder setLang(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lang_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 5 [json_name = "lang"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLang() {
      lang_ = getDefaultInstance().getLang();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 5 [json_name = "lang"];</code>
     * @param value The bytes for lang to set.
     * @return This builder for chaining.
     */
    public Builder setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lang_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * optional tenant/client label for downstream routing
     * </pre>
     *
     * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional tenant/client label for downstream routing
     * </pre>
     *
     * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional tenant/client label for downstream routing
     * </pre>
     *
     * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional tenant/client label for downstream routing
     * </pre>
     *
     * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional tenant/client label for downstream routing
     * </pre>
     *
     * <code>string tenant_id = 6 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long createdAtNs_ ;
    /**
     * <pre>
     * when this event was created
     * </pre>
     *
     * <code>int64 created_at_ns = 7 [json_name = "createdAtNs"];</code>
     * @return The createdAtNs.
     */
    @java.lang.Override
    public long getCreatedAtNs() {
      return createdAtNs_;
    }
    /**
     * <pre>
     * when this event was created
     * </pre>
     *
     * <code>int64 created_at_ns = 7 [json_name = "createdAtNs"];</code>
     * @param value The createdAtNs to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAtNs(long value) {

      createdAtNs_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * when this event was created
     * </pre>
     *
     * <code>int64 created_at_ns = 7 [json_name = "createdAtNs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAtNs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      createdAtNs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RecordingFinished)
  }

  // @@protoc_insertion_point(class_scope:RecordingFinished)
  private static final samuraibff.proto.RecordingFinished DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.RecordingFinished();
  }

  public static samuraibff.proto.RecordingFinished getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordingFinished>
      PARSER = new com.google.protobuf.AbstractParser<RecordingFinished>() {
    @java.lang.Override
    public RecordingFinished parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecordingFinished> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordingFinished> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.RecordingFinished getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

