// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * <pre>
 * One immutable, non-overlapping window from an open session generation.
 * recording.final_plan identifies that generation; timestamps in outputs are
 * absolute within the session, although the WAV contains only this range.
 * </pre>
 *
 * Protobuf type {@code RefinementWindow}
 */
@com.google.protobuf.Generated
public final class RefinementWindow extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RefinementWindow)
    RefinementWindowOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "RefinementWindow");
  }
  // Use RefinementWindow.newBuilder() to construct.
  private RefinementWindow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RefinementWindow() {
    flushReason_ = "";
    bffOriginUri_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_RefinementWindow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_RefinementWindow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.RefinementWindow.class, samuraibff.proto.RefinementWindow.Builder.class);
  }

  private int bitField0_;
  public static final int RECORDING_FIELD_NUMBER = 1;
  private samuraibff.proto.RecordingFinished recording_;
  /**
   * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
   * @return Whether the recording field is set.
   */
  @java.lang.Override
  public boolean hasRecording() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
   * @return The recording.
   */
  @java.lang.Override
  public samuraibff.proto.RecordingFinished getRecording() {
    return recording_ == null ? samuraibff.proto.RecordingFinished.getDefaultInstance() : recording_;
  }
  /**
   * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
   */
  @java.lang.Override
  public samuraibff.proto.RecordingFinishedOrBuilder getRecordingOrBuilder() {
    return recording_ == null ? samuraibff.proto.RecordingFinished.getDefaultInstance() : recording_;
  }

  public static final int START_SAMPLE_FIELD_NUMBER = 2;
  private long startSample_ = 0L;
  /**
   * <code>uint64 start_sample = 2 [json_name = "startSample"];</code>
   * @return The startSample.
   */
  @java.lang.Override
  public long getStartSample() {
    return startSample_;
  }

  public static final int END_SAMPLE_FIELD_NUMBER = 3;
  private long endSample_ = 0L;
  /**
   * <code>uint64 end_sample = 3 [json_name = "endSample"];</code>
   * @return The endSample.
   */
  @java.lang.Override
  public long getEndSample() {
    return endSample_;
  }

  public static final int WINDOW_SAMPLES_FIELD_NUMBER = 4;
  private long windowSamples_ = 0L;
  /**
   * <code>uint64 window_samples = 4 [json_name = "windowSamples"];</code>
   * @return The windowSamples.
   */
  @java.lang.Override
  public long getWindowSamples() {
    return windowSamples_;
  }

  public static final int FLUSH_REASON_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object flushReason_ = "";
  /**
   * <pre>
   * slice | eof | idle
   * </pre>
   *
   * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
   * @return The flushReason.
   */
  @java.lang.Override
  public java.lang.String getFlushReason() {
    java.lang.Object ref = flushReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flushReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * slice | eof | idle
   * </pre>
   *
   * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
   * @return The bytes for flushReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFlushReasonBytes() {
    java.lang.Object ref = flushReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flushReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BFF_ORIGIN_URI_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bffOriginUri_ = "";
  /**
   * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
   * @return The bffOriginUri.
   */
  @java.lang.Override
  public java.lang.String getBffOriginUri() {
    java.lang.Object ref = bffOriginUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bffOriginUri_ = s;
      return s;
    }
  }
  /**
   * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
   * @return The bytes for bffOriginUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBffOriginUriBytes() {
    java.lang.Object ref = bffOriginUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bffOriginUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRecording());
    }
    if (startSample_ != 0L) {
      output.writeUInt64(2, startSample_);
    }
    if (endSample_ != 0L) {
      output.writeUInt64(3, endSample_);
    }
    if (windowSamples_ != 0L) {
      output.writeUInt64(4, windowSamples_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flushReason_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, flushReason_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bffOriginUri_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, bffOriginUri_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRecording());
    }
    if (startSample_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, startSample_);
    }
    if (endSample_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, endSample_);
    }
    if (windowSamples_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, windowSamples_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flushReason_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, flushReason_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bffOriginUri_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, bffOriginUri_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.RefinementWindow)) {
      return super.equals(obj);
    }
    samuraibff.proto.RefinementWindow other = (samuraibff.proto.RefinementWindow) obj;

    if (hasRecording() != other.hasRecording()) return false;
    if (hasRecording()) {
      if (!getRecording()
          .equals(other.getRecording())) return false;
    }
    if (getStartSample()
        != other.getStartSample()) return false;
    if (getEndSample()
        != other.getEndSample()) return false;
    if (getWindowSamples()
        != other.getWindowSamples()) return false;
    if (!getFlushReason()
        .equals(other.getFlushReason())) return false;
    if (!getBffOriginUri()
        .equals(other.getBffOriginUri())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRecording()) {
      hash = (37 * hash) + RECORDING_FIELD_NUMBER;
      hash = (53 * hash) + getRecording().hashCode();
    }
    hash = (37 * hash) + START_SAMPLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartSample());
    hash = (37 * hash) + END_SAMPLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndSample());
    hash = (37 * hash) + WINDOW_SAMPLES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWindowSamples());
    hash = (37 * hash) + FLUSH_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getFlushReason().hashCode();
    hash = (37 * hash) + BFF_ORIGIN_URI_FIELD_NUMBER;
    hash = (53 * hash) + getBffOriginUri().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.RefinementWindow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.RefinementWindow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.RefinementWindow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.RefinementWindow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.RefinementWindow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * One immutable, non-overlapping window from an open session generation.
   * recording.final_plan identifies that generation; timestamps in outputs are
   * absolute within the session, although the WAV contains only this range.
   * </pre>
   *
   * Protobuf type {@code RefinementWindow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RefinementWindow)
      samuraibff.proto.RefinementWindowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_RefinementWindow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_RefinementWindow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.RefinementWindow.class, samuraibff.proto.RefinementWindow.Builder.class);
    }

    // Construct using samuraibff.proto.RefinementWindow.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRecordingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recording_ = null;
      if (recordingBuilder_ != null) {
        recordingBuilder_.dispose();
        recordingBuilder_ = null;
      }
      startSample_ = 0L;
      endSample_ = 0L;
      windowSamples_ = 0L;
      flushReason_ = "";
      bffOriginUri_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_RefinementWindow_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.RefinementWindow getDefaultInstanceForType() {
      return samuraibff.proto.RefinementWindow.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.RefinementWindow build() {
      samuraibff.proto.RefinementWindow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.RefinementWindow buildPartial() {
      samuraibff.proto.RefinementWindow result = new samuraibff.proto.RefinementWindow(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(samuraibff.proto.RefinementWindow result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.recording_ = recordingBuilder_ == null
            ? recording_
            : recordingBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.startSample_ = startSample_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endSample_ = endSample_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.windowSamples_ = windowSamples_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.flushReason_ = flushReason_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.bffOriginUri_ = bffOriginUri_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.RefinementWindow) {
        return mergeFrom((samuraibff.proto.RefinementWindow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.RefinementWindow other) {
      if (other == samuraibff.proto.RefinementWindow.getDefaultInstance()) return this;
      if (other.hasRecording()) {
        mergeRecording(other.getRecording());
      }
      if (other.getStartSample() != 0L) {
        setStartSample(other.getStartSample());
      }
      if (other.getEndSample() != 0L) {
        setEndSample(other.getEndSample());
      }
      if (other.getWindowSamples() != 0L) {
        setWindowSamples(other.getWindowSamples());
      }
      if (!other.getFlushReason().isEmpty()) {
        flushReason_ = other.flushReason_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getBffOriginUri().isEmpty()) {
        bffOriginUri_ = other.bffOriginUri_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRecordingFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              startSample_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              endSample_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              windowSamples_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              flushReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              bffOriginUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private samuraibff.proto.RecordingFinished recording_;
    private com.google.protobuf.SingleFieldBuilder<
        samuraibff.proto.RecordingFinished, samuraibff.proto.RecordingFinished.Builder, samuraibff.proto.RecordingFinishedOrBuilder> recordingBuilder_;
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     * @return Whether the recording field is set.
     */
    public boolean hasRecording() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     * @return The recording.
     */
    public samuraibff.proto.RecordingFinished getRecording() {
      if (recordingBuilder_ == null) {
        return recording_ == null ? samuraibff.proto.RecordingFinished.getDefaultInstance() : recording_;
      } else {
        return recordingBuilder_.getMessage();
      }
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     */
    public Builder setRecording(samuraibff.proto.RecordingFinished value) {
      if (recordingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        recording_ = value;
      } else {
        recordingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     */
    public Builder setRecording(
        samuraibff.proto.RecordingFinished.Builder builderForValue) {
      if (recordingBuilder_ == null) {
        recording_ = builderForValue.build();
      } else {
        recordingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     */
    public Builder mergeRecording(samuraibff.proto.RecordingFinished value) {
      if (recordingBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          recording_ != null &&
          recording_ != samuraibff.proto.RecordingFinished.getDefaultInstance()) {
          getRecordingBuilder().mergeFrom(value);
        } else {
          recording_ = value;
        }
      } else {
        recordingBuilder_.mergeFrom(value);
      }
      if (recording_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     */
    public Builder clearRecording() {
      bitField0_ = (bitField0_ & ~0x00000001);
      recording_ = null;
      if (recordingBuilder_ != null) {
        recordingBuilder_.dispose();
        recordingBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     */
    public samuraibff.proto.RecordingFinished.Builder getRecordingBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetRecordingFieldBuilder().getBuilder();
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     */
    public samuraibff.proto.RecordingFinishedOrBuilder getRecordingOrBuilder() {
      if (recordingBuilder_ != null) {
        return recordingBuilder_.getMessageOrBuilder();
      } else {
        return recording_ == null ?
            samuraibff.proto.RecordingFinished.getDefaultInstance() : recording_;
      }
    }
    /**
     * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        samuraibff.proto.RecordingFinished, samuraibff.proto.RecordingFinished.Builder, samuraibff.proto.RecordingFinishedOrBuilder> 
        internalGetRecordingFieldBuilder() {
      if (recordingBuilder_ == null) {
        recordingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            samuraibff.proto.RecordingFinished, samuraibff.proto.RecordingFinished.Builder, samuraibff.proto.RecordingFinishedOrBuilder>(
                getRecording(),
                getParentForChildren(),
                isClean());
        recording_ = null;
      }
      return recordingBuilder_;
    }

    private long startSample_ ;
    /**
     * <code>uint64 start_sample = 2 [json_name = "startSample"];</code>
     * @return The startSample.
     */
    @java.lang.Override
    public long getStartSample() {
      return startSample_;
    }
    /**
     * <code>uint64 start_sample = 2 [json_name = "startSample"];</code>
     * @param value The startSample to set.
     * @return This builder for chaining.
     */
    public Builder setStartSample(long value) {

      startSample_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 start_sample = 2 [json_name = "startSample"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStartSample() {
      bitField0_ = (bitField0_ & ~0x00000002);
      startSample_ = 0L;
      onChanged();
      return this;
    }

    private long endSample_ ;
    /**
     * <code>uint64 end_sample = 3 [json_name = "endSample"];</code>
     * @return The endSample.
     */
    @java.lang.Override
    public long getEndSample() {
      return endSample_;
    }
    /**
     * <code>uint64 end_sample = 3 [json_name = "endSample"];</code>
     * @param value The endSample to set.
     * @return This builder for chaining.
     */
    public Builder setEndSample(long value) {

      endSample_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 end_sample = 3 [json_name = "endSample"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEndSample() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endSample_ = 0L;
      onChanged();
      return this;
    }

    private long windowSamples_ ;
    /**
     * <code>uint64 window_samples = 4 [json_name = "windowSamples"];</code>
     * @return The windowSamples.
     */
    @java.lang.Override
    public long getWindowSamples() {
      return windowSamples_;
    }
    /**
     * <code>uint64 window_samples = 4 [json_name = "windowSamples"];</code>
     * @param value The windowSamples to set.
     * @return This builder for chaining.
     */
    public Builder setWindowSamples(long value) {

      windowSamples_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 window_samples = 4 [json_name = "windowSamples"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowSamples() {
      bitField0_ = (bitField0_ & ~0x00000008);
      windowSamples_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object flushReason_ = "";
    /**
     * <pre>
     * slice | eof | idle
     * </pre>
     *
     * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
     * @return The flushReason.
     */
    public java.lang.String getFlushReason() {
      java.lang.Object ref = flushReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flushReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * slice | eof | idle
     * </pre>
     *
     * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
     * @return The bytes for flushReason.
     */
    public com.google.protobuf.ByteString
        getFlushReasonBytes() {
      java.lang.Object ref = flushReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flushReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * slice | eof | idle
     * </pre>
     *
     * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
     * @param value The flushReason to set.
     * @return This builder for chaining.
     */
    public Builder setFlushReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      flushReason_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * slice | eof | idle
     * </pre>
     *
     * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFlushReason() {
      flushReason_ = getDefaultInstance().getFlushReason();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * slice | eof | idle
     * </pre>
     *
     * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
     * @param value The bytes for flushReason to set.
     * @return This builder for chaining.
     */
    public Builder setFlushReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      flushReason_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object bffOriginUri_ = "";
    /**
     * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
     * @return The bffOriginUri.
     */
    public java.lang.String getBffOriginUri() {
      java.lang.Object ref = bffOriginUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bffOriginUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
     * @return The bytes for bffOriginUri.
     */
    public com.google.protobuf.ByteString
        getBffOriginUriBytes() {
      java.lang.Object ref = bffOriginUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bffOriginUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
     * @param value The bffOriginUri to set.
     * @return This builder for chaining.
     */
    public Builder setBffOriginUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bffOriginUri_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBffOriginUri() {
      bffOriginUri_ = getDefaultInstance().getBffOriginUri();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
     * @param value The bytes for bffOriginUri to set.
     * @return This builder for chaining.
     */
    public Builder setBffOriginUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bffOriginUri_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RefinementWindow)
  }

  // @@protoc_insertion_point(class_scope:RefinementWindow)
  private static final samuraibff.proto.RefinementWindow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.RefinementWindow();
  }

  public static samuraibff.proto.RefinementWindow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RefinementWindow>
      PARSER = new com.google.protobuf.AbstractParser<RefinementWindow>() {
    @java.lang.Override
    public RefinementWindow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RefinementWindow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RefinementWindow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.RefinementWindow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

