// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface RefinementWindowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RefinementWindow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
   * @return Whether the recording field is set.
   */
  boolean hasRecording();
  /**
   * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
   * @return The recording.
   */
  samuraibff.proto.RecordingFinished getRecording();
  /**
   * <code>.RecordingFinished recording = 1 [json_name = "recording"];</code>
   */
  samuraibff.proto.RecordingFinishedOrBuilder getRecordingOrBuilder();

  /**
   * <code>uint64 start_sample = 2 [json_name = "startSample"];</code>
   * @return The startSample.
   */
  long getStartSample();

  /**
   * <code>uint64 end_sample = 3 [json_name = "endSample"];</code>
   * @return The endSample.
   */
  long getEndSample();

  /**
   * <code>uint64 window_samples = 4 [json_name = "windowSamples"];</code>
   * @return The windowSamples.
   */
  long getWindowSamples();

  /**
   * <pre>
   * slice | eof | idle
   * </pre>
   *
   * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
   * @return The flushReason.
   */
  java.lang.String getFlushReason();
  /**
   * <pre>
   * slice | eof | idle
   * </pre>
   *
   * <code>string flush_reason = 5 [json_name = "flushReason"];</code>
   * @return The bytes for flushReason.
   */
  com.google.protobuf.ByteString
      getFlushReasonBytes();

  /**
   * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
   * @return The bffOriginUri.
   */
  java.lang.String getBffOriginUri();
  /**
   * <code>string bff_origin_uri = 6 [json_name = "bffOriginUri"];</code>
   * @return The bytes for bffOriginUri.
   */
  com.google.protobuf.ByteString
      getBffOriginUriBytes();
}
