// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * Protobuf type {@code RefinedEvent}
 */
@com.google.protobuf.Generated
public final class RefinedEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RefinedEvent)
    RefinedEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "RefinedEvent");
  }
  // Use RefinedEvent.newBuilder() to construct.
  private RefinedEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RefinedEvent() {
    sessionId_ = "";
    text_ = "";
    speaker_ = "";
    supersedesSeq_ = emptyLongList();
    lang_ = "";
    bffOriginUri_ = "";
    tenantId_ = "";
    flushReason_ = "";
    segments_ = java.util.Collections.emptyList();
    refinementModel_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_RefinedEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_RefinedEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.RefinedEvent.class, samuraibff.proto.RefinedEvent.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_S_FIELD_NUMBER = 2;
  private double startS_ = 0D;
  /**
   * <code>double start_s = 2 [json_name = "startS"];</code>
   * @return The startS.
   */
  @java.lang.Override
  public double getStartS() {
    return startS_;
  }

  public static final int END_S_FIELD_NUMBER = 3;
  private double endS_ = 0D;
  /**
   * <code>double end_s = 3 [json_name = "endS"];</code>
   * @return The endS.
   */
  @java.lang.Override
  public double getEndS() {
    return endS_;
  }

  public static final int TEXT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <code>string text = 4 [json_name = "text"];</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 4 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPEAKER_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object speaker_ = "";
  /**
   * <pre>
   * optional/mapped
   * </pre>
   *
   * <code>string speaker = 5 [json_name = "speaker"];</code>
   * @return The speaker.
   */
  @java.lang.Override
  public java.lang.String getSpeaker() {
    java.lang.Object ref = speaker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      speaker_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional/mapped
   * </pre>
   *
   * <code>string speaker = 5 [json_name = "speaker"];</code>
   * @return The bytes for speaker.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpeakerBytes() {
    java.lang.Object ref = speaker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      speaker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUPERSEDES_SEQ_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList supersedesSeq_ =
      emptyLongList();
  /**
   * <pre>
   * optional linkage to live lines
   * </pre>
   *
   * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
   * @return A list containing the supersedesSeq.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getSupersedesSeqList() {
    return supersedesSeq_;
  }
  /**
   * <pre>
   * optional linkage to live lines
   * </pre>
   *
   * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
   * @return The count of supersedesSeq.
   */
  public int getSupersedesSeqCount() {
    return supersedesSeq_.size();
  }
  /**
   * <pre>
   * optional linkage to live lines
   * </pre>
   *
   * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
   * @param index The index of the element to return.
   * @return The supersedesSeq at the given index.
   */
  public long getSupersedesSeq(int index) {
    return supersedesSeq_.getLong(index);
  }
  private int supersedesSeqMemoizedSerializedSize = -1;

  public static final int LANG_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lang_ = "";
  /**
   * <code>string lang = 7 [json_name = "lang"];</code>
   * @return The lang.
   */
  @java.lang.Override
  public java.lang.String getLang() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lang_ = s;
      return s;
    }
  }
  /**
   * <code>string lang = 7 [json_name = "lang"];</code>
   * @return The bytes for lang.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLangBytes() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BFF_ORIGIN_URI_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bffOriginUri_ = "";
  /**
   * <pre>
   * Base URI of the BFF instance that originated this session.
   * This value is copied from AudioChunk.bff_origin_uri by the worker.
   * </pre>
   *
   * <code>string bff_origin_uri = 8 [json_name = "bffOriginUri"];</code>
   * @return The bffOriginUri.
   */
  @java.lang.Override
  public java.lang.String getBffOriginUri() {
    java.lang.Object ref = bffOriginUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bffOriginUri_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Base URI of the BFF instance that originated this session.
   * This value is copied from AudioChunk.bff_origin_uri by the worker.
   * </pre>
   *
   * <code>string bff_origin_uri = 8 [json_name = "bffOriginUri"];</code>
   * @return The bytes for bffOriginUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBffOriginUriBytes() {
    java.lang.Object ref = bffOriginUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bffOriginUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * Tenant id for routing/isolation.
   * This value is copied from AudioChunk.tenant_id by the worker.
   * </pre>
   *
   * <code>string tenant_id = 9 [json_name = "tenantId"];</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tenant id for routing/isolation.
   * This value is copied from AudioChunk.tenant_id by the worker.
   * </pre>
   *
   * <code>string tenant_id = 9 [json_name = "tenantId"];</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WINDOW_SEC_FIELD_NUMBER = 10;
  private double windowSec_ = 0D;
  /**
   * <pre>
   * Identity and timing of the refinement window.
   * NOTE: the window boundaries are represented by start_s/end_s.
   * </pre>
   *
   * <code>double window_sec = 10 [json_name = "windowSec"];</code>
   * @return The windowSec.
   */
  @java.lang.Override
  public double getWindowSec() {
    return windowSec_;
  }

  public static final int SLICE_INDEX_FIELD_NUMBER = 11;
  private int sliceIndex_ = 0;
  /**
   * <pre>
   * 0-based index for this window size
   * </pre>
   *
   * <code>uint32 slice_index = 11 [json_name = "sliceIndex"];</code>
   * @return The sliceIndex.
   */
  @java.lang.Override
  public int getSliceIndex() {
    return sliceIndex_;
  }

  public static final int FLUSH_REASON_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object flushReason_ = "";
  /**
   * <pre>
   * "slice" | "idle" (idle = final shorter tail)
   * </pre>
   *
   * <code>string flush_reason = 12 [json_name = "flushReason"];</code>
   * @return The flushReason.
   */
  @java.lang.Override
  public java.lang.String getFlushReason() {
    java.lang.Object ref = flushReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flushReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "slice" | "idle" (idle = final shorter tail)
   * </pre>
   *
   * <code>string flush_reason = 12 [json_name = "flushReason"];</code>
   * @return The bytes for flushReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFlushReasonBytes() {
    java.lang.Object ref = flushReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flushReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENTS_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private java.util.List<samuraibff.proto.SessionTranscriptSegment> segments_;
  /**
   * <pre>
   * The refined transcript for this window (speaker turns).
   * </pre>
   *
   * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
   */
  @java.lang.Override
  public java.util.List<samuraibff.proto.SessionTranscriptSegment> getSegmentsList() {
    return segments_;
  }
  /**
   * <pre>
   * The refined transcript for this window (speaker turns).
   * </pre>
   *
   * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
      getSegmentsOrBuilderList() {
    return segments_;
  }
  /**
   * <pre>
   * The refined transcript for this window (speaker turns).
   * </pre>
   *
   * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
   */
  @java.lang.Override
  public int getSegmentsCount() {
    return segments_.size();
  }
  /**
   * <pre>
   * The refined transcript for this window (speaker turns).
   * </pre>
   *
   * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
   */
  @java.lang.Override
  public samuraibff.proto.SessionTranscriptSegment getSegments(int index) {
    return segments_.get(index);
  }
  /**
   * <pre>
   * The refined transcript for this window (speaker turns).
   * </pre>
   *
   * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
   */
  @java.lang.Override
  public samuraibff.proto.SessionTranscriptSegmentOrBuilder getSegmentsOrBuilder(
      int index) {
    return segments_.get(index);
  }

  public static final int CREATED_AT_NS_FIELD_NUMBER = 14;
  private long createdAtNs_ = 0L;
  /**
   * <pre>
   * Optional metadata for dedupe/ordering.
   * </pre>
   *
   * <code>uint64 created_at_ns = 14 [json_name = "createdAtNs"];</code>
   * @return The createdAtNs.
   */
  @java.lang.Override
  public long getCreatedAtNs() {
    return createdAtNs_;
  }

  public static final int REFINEMENT_MODEL_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object refinementModel_ = "";
  /**
   * <pre>
   * e.g. "whisperx" (future: voxstral, ...)
   * </pre>
   *
   * <code>string refinement_model = 15 [json_name = "refinementModel"];</code>
   * @return The refinementModel.
   */
  @java.lang.Override
  public java.lang.String getRefinementModel() {
    java.lang.Object ref = refinementModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refinementModel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g. "whisperx" (future: voxstral, ...)
   * </pre>
   *
   * <code>string refinement_model = 15 [json_name = "refinementModel"];</code>
   * @return The bytes for refinementModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefinementModelBytes() {
    java.lang.Object ref = refinementModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refinementModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (java.lang.Double.doubleToRawLongBits(startS_) != 0) {
      output.writeDouble(2, startS_);
    }
    if (java.lang.Double.doubleToRawLongBits(endS_) != 0) {
      output.writeDouble(3, endS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, text_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(speaker_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, speaker_);
    }
    if (getSupersedesSeqList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(supersedesSeqMemoizedSerializedSize);
    }
    for (int i = 0; i < supersedesSeq_.size(); i++) {
      output.writeUInt64NoTag(supersedesSeq_.getLong(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, lang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bffOriginUri_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, bffOriginUri_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, tenantId_);
    }
    if (java.lang.Double.doubleToRawLongBits(windowSec_) != 0) {
      output.writeDouble(10, windowSec_);
    }
    if (sliceIndex_ != 0) {
      output.writeUInt32(11, sliceIndex_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flushReason_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, flushReason_);
    }
    for (int i = 0; i < segments_.size(); i++) {
      output.writeMessage(13, segments_.get(i));
    }
    if (createdAtNs_ != 0L) {
      output.writeUInt64(14, createdAtNs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(refinementModel_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 15, refinementModel_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (java.lang.Double.doubleToRawLongBits(startS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, startS_);
    }
    if (java.lang.Double.doubleToRawLongBits(endS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, endS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, text_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(speaker_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, speaker_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < supersedesSeq_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(supersedesSeq_.getLong(i));
      }
      size += dataSize;
      if (!getSupersedesSeqList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      supersedesSeqMemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, lang_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bffOriginUri_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, bffOriginUri_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, tenantId_);
    }
    if (java.lang.Double.doubleToRawLongBits(windowSec_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, windowSec_);
    }
    if (sliceIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(11, sliceIndex_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flushReason_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, flushReason_);
    }
    for (int i = 0; i < segments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, segments_.get(i));
    }
    if (createdAtNs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(14, createdAtNs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(refinementModel_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(15, refinementModel_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.RefinedEvent)) {
      return super.equals(obj);
    }
    samuraibff.proto.RefinedEvent other = (samuraibff.proto.RefinedEvent) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (java.lang.Double.doubleToLongBits(getStartS())
        != java.lang.Double.doubleToLongBits(
            other.getStartS())) return false;
    if (java.lang.Double.doubleToLongBits(getEndS())
        != java.lang.Double.doubleToLongBits(
            other.getEndS())) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (!getSpeaker()
        .equals(other.getSpeaker())) return false;
    if (!getSupersedesSeqList()
        .equals(other.getSupersedesSeqList())) return false;
    if (!getLang()
        .equals(other.getLang())) return false;
    if (!getBffOriginUri()
        .equals(other.getBffOriginUri())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (java.lang.Double.doubleToLongBits(getWindowSec())
        != java.lang.Double.doubleToLongBits(
            other.getWindowSec())) return false;
    if (getSliceIndex()
        != other.getSliceIndex()) return false;
    if (!getFlushReason()
        .equals(other.getFlushReason())) return false;
    if (!getSegmentsList()
        .equals(other.getSegmentsList())) return false;
    if (getCreatedAtNs()
        != other.getCreatedAtNs()) return false;
    if (!getRefinementModel()
        .equals(other.getRefinementModel())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + START_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getStartS()));
    hash = (37 * hash) + END_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEndS()));
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + SPEAKER_FIELD_NUMBER;
    hash = (53 * hash) + getSpeaker().hashCode();
    if (getSupersedesSeqCount() > 0) {
      hash = (37 * hash) + SUPERSEDES_SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSupersedesSeqList().hashCode();
    }
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + getLang().hashCode();
    hash = (37 * hash) + BFF_ORIGIN_URI_FIELD_NUMBER;
    hash = (53 * hash) + getBffOriginUri().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + WINDOW_SEC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWindowSec()));
    hash = (37 * hash) + SLICE_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getSliceIndex();
    hash = (37 * hash) + FLUSH_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getFlushReason().hashCode();
    if (getSegmentsCount() > 0) {
      hash = (37 * hash) + SEGMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getSegmentsList().hashCode();
    }
    hash = (37 * hash) + CREATED_AT_NS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAtNs());
    hash = (37 * hash) + REFINEMENT_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getRefinementModel().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.RefinedEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.RefinedEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.RefinedEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.RefinedEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.RefinedEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RefinedEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RefinedEvent)
      samuraibff.proto.RefinedEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_RefinedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_RefinedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.RefinedEvent.class, samuraibff.proto.RefinedEvent.Builder.class);
    }

    // Construct using samuraibff.proto.RefinedEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      startS_ = 0D;
      endS_ = 0D;
      text_ = "";
      speaker_ = "";
      supersedesSeq_ = emptyLongList();
      lang_ = "";
      bffOriginUri_ = "";
      tenantId_ = "";
      windowSec_ = 0D;
      sliceIndex_ = 0;
      flushReason_ = "";
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
      } else {
        segments_ = null;
        segmentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00001000);
      createdAtNs_ = 0L;
      refinementModel_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_RefinedEvent_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.RefinedEvent getDefaultInstanceForType() {
      return samuraibff.proto.RefinedEvent.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.RefinedEvent build() {
      samuraibff.proto.RefinedEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.RefinedEvent buildPartial() {
      samuraibff.proto.RefinedEvent result = new samuraibff.proto.RefinedEvent(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(samuraibff.proto.RefinedEvent result) {
      if (segmentsBuilder_ == null) {
        if (((bitField0_ & 0x00001000) != 0)) {
          segments_ = java.util.Collections.unmodifiableList(segments_);
          bitField0_ = (bitField0_ & ~0x00001000);
        }
        result.segments_ = segments_;
      } else {
        result.segments_ = segmentsBuilder_.build();
      }
    }

    private void buildPartial0(samuraibff.proto.RefinedEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.startS_ = startS_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endS_ = endS_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.text_ = text_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.speaker_ = speaker_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        supersedesSeq_.makeImmutable();
        result.supersedesSeq_ = supersedesSeq_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.lang_ = lang_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.bffOriginUri_ = bffOriginUri_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.windowSec_ = windowSec_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.sliceIndex_ = sliceIndex_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.flushReason_ = flushReason_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.createdAtNs_ = createdAtNs_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.refinementModel_ = refinementModel_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.RefinedEvent) {
        return mergeFrom((samuraibff.proto.RefinedEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.RefinedEvent other) {
      if (other == samuraibff.proto.RefinedEvent.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getStartS()) != 0) {
        setStartS(other.getStartS());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getEndS()) != 0) {
        setEndS(other.getEndS());
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getSpeaker().isEmpty()) {
        speaker_ = other.speaker_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.supersedesSeq_.isEmpty()) {
        if (supersedesSeq_.isEmpty()) {
          supersedesSeq_ = other.supersedesSeq_;
          supersedesSeq_.makeImmutable();
          bitField0_ |= 0x00000020;
        } else {
          ensureSupersedesSeqIsMutable();
          supersedesSeq_.addAll(other.supersedesSeq_);
        }
        onChanged();
      }
      if (!other.getLang().isEmpty()) {
        lang_ = other.lang_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getBffOriginUri().isEmpty()) {
        bffOriginUri_ = other.bffOriginUri_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getWindowSec()) != 0) {
        setWindowSec(other.getWindowSec());
      }
      if (other.getSliceIndex() != 0) {
        setSliceIndex(other.getSliceIndex());
      }
      if (!other.getFlushReason().isEmpty()) {
        flushReason_ = other.flushReason_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (segmentsBuilder_ == null) {
        if (!other.segments_.isEmpty()) {
          if (segments_.isEmpty()) {
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00001000);
          } else {
            ensureSegmentsIsMutable();
            segments_.addAll(other.segments_);
          }
          onChanged();
        }
      } else {
        if (!other.segments_.isEmpty()) {
          if (segmentsBuilder_.isEmpty()) {
            segmentsBuilder_.dispose();
            segmentsBuilder_ = null;
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00001000);
            segmentsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSegmentsFieldBuilder() : null;
          } else {
            segmentsBuilder_.addAllMessages(other.segments_);
          }
        }
      }
      if (other.getCreatedAtNs() != 0L) {
        setCreatedAtNs(other.getCreatedAtNs());
      }
      if (!other.getRefinementModel().isEmpty()) {
        refinementModel_ = other.refinementModel_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              startS_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              endS_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              speaker_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              long v = input.readUInt64();
              ensureSupersedesSeqIsMutable();
              supersedesSeq_.addLong(v);
              break;
            } // case 48
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureSupersedesSeqIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                supersedesSeq_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            } // case 50
            case 58: {
              lang_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              bffOriginUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 81: {
              windowSec_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 88: {
              sliceIndex_ = input.readUInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              flushReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              samuraibff.proto.SessionTranscriptSegment m =
                  input.readMessage(
                      samuraibff.proto.SessionTranscriptSegment.parser(),
                      extensionRegistry);
              if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.add(m);
              } else {
                segmentsBuilder_.addMessage(m);
              }
              break;
            } // case 106
            case 112: {
              createdAtNs_ = input.readUInt64();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 122: {
              refinementModel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double startS_ ;
    /**
     * <code>double start_s = 2 [json_name = "startS"];</code>
     * @return The startS.
     */
    @java.lang.Override
    public double getStartS() {
      return startS_;
    }
    /**
     * <code>double start_s = 2 [json_name = "startS"];</code>
     * @param value The startS to set.
     * @return This builder for chaining.
     */
    public Builder setStartS(double value) {

      startS_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double start_s = 2 [json_name = "startS"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStartS() {
      bitField0_ = (bitField0_ & ~0x00000002);
      startS_ = 0D;
      onChanged();
      return this;
    }

    private double endS_ ;
    /**
     * <code>double end_s = 3 [json_name = "endS"];</code>
     * @return The endS.
     */
    @java.lang.Override
    public double getEndS() {
      return endS_;
    }
    /**
     * <code>double end_s = 3 [json_name = "endS"];</code>
     * @param value The endS to set.
     * @return This builder for chaining.
     */
    public Builder setEndS(double value) {

      endS_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double end_s = 3 [json_name = "endS"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEndS() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endS_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 4 [json_name = "text"];</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 4 [json_name = "text"];</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 4 [json_name = "text"];</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 4 [json_name = "text"];</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string text = 4 [json_name = "text"];</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object speaker_ = "";
    /**
     * <pre>
     * optional/mapped
     * </pre>
     *
     * <code>string speaker = 5 [json_name = "speaker"];</code>
     * @return The speaker.
     */
    public java.lang.String getSpeaker() {
      java.lang.Object ref = speaker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        speaker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional/mapped
     * </pre>
     *
     * <code>string speaker = 5 [json_name = "speaker"];</code>
     * @return The bytes for speaker.
     */
    public com.google.protobuf.ByteString
        getSpeakerBytes() {
      java.lang.Object ref = speaker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        speaker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional/mapped
     * </pre>
     *
     * <code>string speaker = 5 [json_name = "speaker"];</code>
     * @param value The speaker to set.
     * @return This builder for chaining.
     */
    public Builder setSpeaker(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      speaker_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional/mapped
     * </pre>
     *
     * <code>string speaker = 5 [json_name = "speaker"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeaker() {
      speaker_ = getDefaultInstance().getSpeaker();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional/mapped
     * </pre>
     *
     * <code>string speaker = 5 [json_name = "speaker"];</code>
     * @param value The bytes for speaker to set.
     * @return This builder for chaining.
     */
    public Builder setSpeakerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      speaker_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList supersedesSeq_ = emptyLongList();
    private void ensureSupersedesSeqIsMutable() {
      if (!supersedesSeq_.isModifiable()) {
        supersedesSeq_ = makeMutableCopy(supersedesSeq_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <pre>
     * optional linkage to live lines
     * </pre>
     *
     * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
     * @return A list containing the supersedesSeq.
     */
    public java.util.List<java.lang.Long>
        getSupersedesSeqList() {
      supersedesSeq_.makeImmutable();
      return supersedesSeq_;
    }
    /**
     * <pre>
     * optional linkage to live lines
     * </pre>
     *
     * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
     * @return The count of supersedesSeq.
     */
    public int getSupersedesSeqCount() {
      return supersedesSeq_.size();
    }
    /**
     * <pre>
     * optional linkage to live lines
     * </pre>
     *
     * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
     * @param index The index of the element to return.
     * @return The supersedesSeq at the given index.
     */
    public long getSupersedesSeq(int index) {
      return supersedesSeq_.getLong(index);
    }
    /**
     * <pre>
     * optional linkage to live lines
     * </pre>
     *
     * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
     * @param index The index to set the value at.
     * @param value The supersedesSeq to set.
     * @return This builder for chaining.
     */
    public Builder setSupersedesSeq(
        int index, long value) {

      ensureSupersedesSeqIsMutable();
      supersedesSeq_.setLong(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional linkage to live lines
     * </pre>
     *
     * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
     * @param value The supersedesSeq to add.
     * @return This builder for chaining.
     */
    public Builder addSupersedesSeq(long value) {

      ensureSupersedesSeqIsMutable();
      supersedesSeq_.addLong(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional linkage to live lines
     * </pre>
     *
     * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
     * @param values The supersedesSeq to add.
     * @return This builder for chaining.
     */
    public Builder addAllSupersedesSeq(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureSupersedesSeqIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, supersedesSeq_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional linkage to live lines
     * </pre>
     *
     * <code>repeated uint64 supersedes_seq = 6 [json_name = "supersedesSeq"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSupersedesSeq() {
      supersedesSeq_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    private java.lang.Object lang_ = "";
    /**
     * <code>string lang = 7 [json_name = "lang"];</code>
     * @return The lang.
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lang = 7 [json_name = "lang"];</code>
     * @return The bytes for lang.
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lang = 7 [json_name = "lang"];</code>
     * @param value The lang to set.
     * @return This builder for chaining.
     */
    public Builder setLang(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lang_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 7 [json_name = "lang"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLang() {
      lang_ = getDefaultInstance().getLang();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 7 [json_name = "lang"];</code>
     * @param value The bytes for lang to set.
     * @return This builder for chaining.
     */
    public Builder setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lang_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object bffOriginUri_ = "";
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * This value is copied from AudioChunk.bff_origin_uri by the worker.
     * </pre>
     *
     * <code>string bff_origin_uri = 8 [json_name = "bffOriginUri"];</code>
     * @return The bffOriginUri.
     */
    public java.lang.String getBffOriginUri() {
      java.lang.Object ref = bffOriginUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bffOriginUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * This value is copied from AudioChunk.bff_origin_uri by the worker.
     * </pre>
     *
     * <code>string bff_origin_uri = 8 [json_name = "bffOriginUri"];</code>
     * @return The bytes for bffOriginUri.
     */
    public com.google.protobuf.ByteString
        getBffOriginUriBytes() {
      java.lang.Object ref = bffOriginUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bffOriginUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * This value is copied from AudioChunk.bff_origin_uri by the worker.
     * </pre>
     *
     * <code>string bff_origin_uri = 8 [json_name = "bffOriginUri"];</code>
     * @param value The bffOriginUri to set.
     * @return This builder for chaining.
     */
    public Builder setBffOriginUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bffOriginUri_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * This value is copied from AudioChunk.bff_origin_uri by the worker.
     * </pre>
     *
     * <code>string bff_origin_uri = 8 [json_name = "bffOriginUri"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBffOriginUri() {
      bffOriginUri_ = getDefaultInstance().getBffOriginUri();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Base URI of the BFF instance that originated this session.
     * This value is copied from AudioChunk.bff_origin_uri by the worker.
     * </pre>
     *
     * <code>string bff_origin_uri = 8 [json_name = "bffOriginUri"];</code>
     * @param value The bytes for bffOriginUri to set.
     * @return This builder for chaining.
     */
    public Builder setBffOriginUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bffOriginUri_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * This value is copied from AudioChunk.tenant_id by the worker.
     * </pre>
     *
     * <code>string tenant_id = 9 [json_name = "tenantId"];</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * This value is copied from AudioChunk.tenant_id by the worker.
     * </pre>
     *
     * <code>string tenant_id = 9 [json_name = "tenantId"];</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * This value is copied from AudioChunk.tenant_id by the worker.
     * </pre>
     *
     * <code>string tenant_id = 9 [json_name = "tenantId"];</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * This value is copied from AudioChunk.tenant_id by the worker.
     * </pre>
     *
     * <code>string tenant_id = 9 [json_name = "tenantId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant id for routing/isolation.
     * This value is copied from AudioChunk.tenant_id by the worker.
     * </pre>
     *
     * <code>string tenant_id = 9 [json_name = "tenantId"];</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private double windowSec_ ;
    /**
     * <pre>
     * Identity and timing of the refinement window.
     * NOTE: the window boundaries are represented by start_s/end_s.
     * </pre>
     *
     * <code>double window_sec = 10 [json_name = "windowSec"];</code>
     * @return The windowSec.
     */
    @java.lang.Override
    public double getWindowSec() {
      return windowSec_;
    }
    /**
     * <pre>
     * Identity and timing of the refinement window.
     * NOTE: the window boundaries are represented by start_s/end_s.
     * </pre>
     *
     * <code>double window_sec = 10 [json_name = "windowSec"];</code>
     * @param value The windowSec to set.
     * @return This builder for chaining.
     */
    public Builder setWindowSec(double value) {

      windowSec_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identity and timing of the refinement window.
     * NOTE: the window boundaries are represented by start_s/end_s.
     * </pre>
     *
     * <code>double window_sec = 10 [json_name = "windowSec"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowSec() {
      bitField0_ = (bitField0_ & ~0x00000200);
      windowSec_ = 0D;
      onChanged();
      return this;
    }

    private int sliceIndex_ ;
    /**
     * <pre>
     * 0-based index for this window size
     * </pre>
     *
     * <code>uint32 slice_index = 11 [json_name = "sliceIndex"];</code>
     * @return The sliceIndex.
     */
    @java.lang.Override
    public int getSliceIndex() {
      return sliceIndex_;
    }
    /**
     * <pre>
     * 0-based index for this window size
     * </pre>
     *
     * <code>uint32 slice_index = 11 [json_name = "sliceIndex"];</code>
     * @param value The sliceIndex to set.
     * @return This builder for chaining.
     */
    public Builder setSliceIndex(int value) {

      sliceIndex_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0-based index for this window size
     * </pre>
     *
     * <code>uint32 slice_index = 11 [json_name = "sliceIndex"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSliceIndex() {
      bitField0_ = (bitField0_ & ~0x00000400);
      sliceIndex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object flushReason_ = "";
    /**
     * <pre>
     * "slice" | "idle" (idle = final shorter tail)
     * </pre>
     *
     * <code>string flush_reason = 12 [json_name = "flushReason"];</code>
     * @return The flushReason.
     */
    public java.lang.String getFlushReason() {
      java.lang.Object ref = flushReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flushReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "slice" | "idle" (idle = final shorter tail)
     * </pre>
     *
     * <code>string flush_reason = 12 [json_name = "flushReason"];</code>
     * @return The bytes for flushReason.
     */
    public com.google.protobuf.ByteString
        getFlushReasonBytes() {
      java.lang.Object ref = flushReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flushReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "slice" | "idle" (idle = final shorter tail)
     * </pre>
     *
     * <code>string flush_reason = 12 [json_name = "flushReason"];</code>
     * @param value The flushReason to set.
     * @return This builder for chaining.
     */
    public Builder setFlushReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      flushReason_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "slice" | "idle" (idle = final shorter tail)
     * </pre>
     *
     * <code>string flush_reason = 12 [json_name = "flushReason"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFlushReason() {
      flushReason_ = getDefaultInstance().getFlushReason();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "slice" | "idle" (idle = final shorter tail)
     * </pre>
     *
     * <code>string flush_reason = 12 [json_name = "flushReason"];</code>
     * @param value The bytes for flushReason to set.
     * @return This builder for chaining.
     */
    public Builder setFlushReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      flushReason_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.util.List<samuraibff.proto.SessionTranscriptSegment> segments_ =
      java.util.Collections.emptyList();
    private void ensureSegmentsIsMutable() {
      if (!((bitField0_ & 0x00001000) != 0)) {
        segments_ = new java.util.ArrayList<samuraibff.proto.SessionTranscriptSegment>(segments_);
        bitField0_ |= 0x00001000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.SessionTranscriptSegment, samuraibff.proto.SessionTranscriptSegment.Builder, samuraibff.proto.SessionTranscriptSegmentOrBuilder> segmentsBuilder_;

    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public java.util.List<samuraibff.proto.SessionTranscriptSegment> getSegmentsList() {
      if (segmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(segments_);
      } else {
        return segmentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public int getSegmentsCount() {
      if (segmentsBuilder_ == null) {
        return segments_.size();
      } else {
        return segmentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public samuraibff.proto.SessionTranscriptSegment getSegments(int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);
      } else {
        return segmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder setSegments(
        int index, samuraibff.proto.SessionTranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.set(index, value);
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder setSegments(
        int index, samuraibff.proto.SessionTranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.set(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder addSegments(samuraibff.proto.SessionTranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder addSegments(
        int index, samuraibff.proto.SessionTranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(index, value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder addSegments(
        samuraibff.proto.SessionTranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder addSegments(
        int index, samuraibff.proto.SessionTranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder addAllSegments(
        java.lang.Iterable<? extends samuraibff.proto.SessionTranscriptSegment> values) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, segments_);
        onChanged();
      } else {
        segmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder clearSegments() {
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
      } else {
        segmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public Builder removeSegments(int index) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.remove(index);
        onChanged();
      } else {
        segmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public samuraibff.proto.SessionTranscriptSegment.Builder getSegmentsBuilder(
        int index) {
      return internalGetSegmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public samuraibff.proto.SessionTranscriptSegmentOrBuilder getSegmentsOrBuilder(
        int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);  } else {
        return segmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public java.util.List<? extends samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
         getSegmentsOrBuilderList() {
      if (segmentsBuilder_ != null) {
        return segmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(segments_);
      }
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public samuraibff.proto.SessionTranscriptSegment.Builder addSegmentsBuilder() {
      return internalGetSegmentsFieldBuilder().addBuilder(
          samuraibff.proto.SessionTranscriptSegment.getDefaultInstance());
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public samuraibff.proto.SessionTranscriptSegment.Builder addSegmentsBuilder(
        int index) {
      return internalGetSegmentsFieldBuilder().addBuilder(
          index, samuraibff.proto.SessionTranscriptSegment.getDefaultInstance());
    }
    /**
     * <pre>
     * The refined transcript for this window (speaker turns).
     * </pre>
     *
     * <code>repeated .SessionTranscriptSegment segments = 13 [json_name = "segments"];</code>
     */
    public java.util.List<samuraibff.proto.SessionTranscriptSegment.Builder> 
         getSegmentsBuilderList() {
      return internalGetSegmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.SessionTranscriptSegment, samuraibff.proto.SessionTranscriptSegment.Builder, samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
        internalGetSegmentsFieldBuilder() {
      if (segmentsBuilder_ == null) {
        segmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            samuraibff.proto.SessionTranscriptSegment, samuraibff.proto.SessionTranscriptSegment.Builder, samuraibff.proto.SessionTranscriptSegmentOrBuilder>(
                segments_,
                ((bitField0_ & 0x00001000) != 0),
                getParentForChildren(),
                isClean());
        segments_ = null;
      }
      return segmentsBuilder_;
    }

    private long createdAtNs_ ;
    /**
     * <pre>
     * Optional metadata for dedupe/ordering.
     * </pre>
     *
     * <code>uint64 created_at_ns = 14 [json_name = "createdAtNs"];</code>
     * @return The createdAtNs.
     */
    @java.lang.Override
    public long getCreatedAtNs() {
      return createdAtNs_;
    }
    /**
     * <pre>
     * Optional metadata for dedupe/ordering.
     * </pre>
     *
     * <code>uint64 created_at_ns = 14 [json_name = "createdAtNs"];</code>
     * @param value The createdAtNs to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAtNs(long value) {

      createdAtNs_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional metadata for dedupe/ordering.
     * </pre>
     *
     * <code>uint64 created_at_ns = 14 [json_name = "createdAtNs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAtNs() {
      bitField0_ = (bitField0_ & ~0x00002000);
      createdAtNs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object refinementModel_ = "";
    /**
     * <pre>
     * e.g. "whisperx" (future: voxstral, ...)
     * </pre>
     *
     * <code>string refinement_model = 15 [json_name = "refinementModel"];</code>
     * @return The refinementModel.
     */
    public java.lang.String getRefinementModel() {
      java.lang.Object ref = refinementModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refinementModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. "whisperx" (future: voxstral, ...)
     * </pre>
     *
     * <code>string refinement_model = 15 [json_name = "refinementModel"];</code>
     * @return The bytes for refinementModel.
     */
    public com.google.protobuf.ByteString
        getRefinementModelBytes() {
      java.lang.Object ref = refinementModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refinementModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. "whisperx" (future: voxstral, ...)
     * </pre>
     *
     * <code>string refinement_model = 15 [json_name = "refinementModel"];</code>
     * @param value The refinementModel to set.
     * @return This builder for chaining.
     */
    public Builder setRefinementModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      refinementModel_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "whisperx" (future: voxstral, ...)
     * </pre>
     *
     * <code>string refinement_model = 15 [json_name = "refinementModel"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRefinementModel() {
      refinementModel_ = getDefaultInstance().getRefinementModel();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "whisperx" (future: voxstral, ...)
     * </pre>
     *
     * <code>string refinement_model = 15 [json_name = "refinementModel"];</code>
     * @param value The bytes for refinementModel to set.
     * @return This builder for chaining.
     */
    public Builder setRefinementModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      refinementModel_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RefinedEvent)
  }

  // @@protoc_insertion_point(class_scope:RefinedEvent)
  private static final samuraibff.proto.RefinedEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.RefinedEvent();
  }

  public static samuraibff.proto.RefinedEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RefinedEvent>
      PARSER = new com.google.protobuf.AbstractParser<RefinedEvent>() {
    @java.lang.Override
    public RefinedEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RefinedEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RefinedEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.RefinedEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

