// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface SessionTranscriptSegmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SessionTranscriptSegment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double start_s = 1 [json_name = "startS"];</code>
   * @return The startS.
   */
  double getStartS();

  /**
   * <code>double end_s = 2 [json_name = "endS"];</code>
   * @return The endS.
   */
  double getEndS();

  /**
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * optional, "" if unknown
   * </pre>
   *
   * <code>string speaker = 4 [json_name = "speaker"];</code>
   * @return The speaker.
   */
  java.lang.String getSpeaker();
  /**
   * <pre>
   * optional, "" if unknown
   * </pre>
   *
   * <code>string speaker = 4 [json_name = "speaker"];</code>
   * @return The bytes for speaker.
   */
  com.google.protobuf.ByteString
      getSpeakerBytes();
}
