// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface SessionTranscriptSegmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SessionTranscriptSegment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double start_s = 1;</code>
   * @return The startS.
   */
  double getStartS();

  /**
   * <code>double end_s = 2;</code>
   * @return The endS.
   */
  double getEndS();

  /**
   * <code>string text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * optional, "" if unknown
   * </pre>
   *
   * <code>string speaker = 4;</code>
   * @return The speaker.
   */
  java.lang.String getSpeaker();
  /**
   * <pre>
   * optional, "" if unknown
   * </pre>
   *
   * <code>string speaker = 4;</code>
   * @return The bytes for speaker.
   */
  com.google.protobuf.ByteString
      getSpeakerBytes();

  /**
   * <pre>
   * Optional word-level alignment details as produced by the xamurai finalizer.
   * If absent (older producers) or empty, consumers should treat the segment as
   * having no word-level timing information.
   * </pre>
   *
   * <code>repeated .WordAlignment words = 5;</code>
   */
  java.util.List<samuraibff.proto.WordAlignment> 
      getWordsList();
  /**
   * <pre>
   * Optional word-level alignment details as produced by the xamurai finalizer.
   * If absent (older producers) or empty, consumers should treat the segment as
   * having no word-level timing information.
   * </pre>
   *
   * <code>repeated .WordAlignment words = 5;</code>
   */
  samuraibff.proto.WordAlignment getWords(int index);
  /**
   * <pre>
   * Optional word-level alignment details as produced by the xamurai finalizer.
   * If absent (older producers) or empty, consumers should treat the segment as
   * having no word-level timing information.
   * </pre>
   *
   * <code>repeated .WordAlignment words = 5;</code>
   */
  int getWordsCount();
  /**
   * <pre>
   * Optional word-level alignment details as produced by the xamurai finalizer.
   * If absent (older producers) or empty, consumers should treat the segment as
   * having no word-level timing information.
   * </pre>
   *
   * <code>repeated .WordAlignment words = 5;</code>
   */
  java.util.List<? extends samuraibff.proto.WordAlignmentOrBuilder> 
      getWordsOrBuilderList();
  /**
   * <pre>
   * Optional word-level alignment details as produced by the xamurai finalizer.
   * If absent (older producers) or empty, consumers should treat the segment as
   * having no word-level timing information.
   * </pre>
   *
   * <code>repeated .WordAlignment words = 5;</code>
   */
  samuraibff.proto.WordAlignmentOrBuilder getWordsOrBuilder(
      int index);
}
