// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * Protobuf type {@code SessionTranscript}
 */
@com.google.protobuf.Generated
public final class SessionTranscript extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SessionTranscript)
    SessionTranscriptOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "SessionTranscript");
  }
  // Use SessionTranscript.newBuilder() to construct.
  private SessionTranscript(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SessionTranscript() {
    sessionId_ = "";
    recordingUrl_ = "";
    lang_ = "";
    segments_ = java.util.Collections.emptyList();
    fullText_ = "";
    tenantId_ = "";
    trackId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_SessionTranscript_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_SessionTranscript_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.SessionTranscript.class, samuraibff.proto.SessionTranscript.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDING_URL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recordingUrl_ = "";
  /**
   * <code>string recording_url = 2;</code>
   * @return The recordingUrl.
   */
  @java.lang.Override
  public java.lang.String getRecordingUrl() {
    java.lang.Object ref = recordingUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordingUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string recording_url = 2;</code>
   * @return The bytes for recordingUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecordingUrlBytes() {
    java.lang.Object ref = recordingUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordingUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANG_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lang_ = "";
  /**
   * <code>string lang = 3;</code>
   * @return The lang.
   */
  @java.lang.Override
  public java.lang.String getLang() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lang_ = s;
      return s;
    }
  }
  /**
   * <code>string lang = 3;</code>
   * @return The bytes for lang.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLangBytes() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_S_FIELD_NUMBER = 4;
  private float durationS_ = 0F;
  /**
   * <code>float duration_s = 4;</code>
   * @return The durationS.
   */
  @java.lang.Override
  public float getDurationS() {
    return durationS_;
  }

  public static final int SEGMENTS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<samuraibff.proto.SessionTranscriptSegment> segments_;
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  @java.lang.Override
  public java.util.List<samuraibff.proto.SessionTranscriptSegment> getSegmentsList() {
    return segments_;
  }
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
      getSegmentsOrBuilderList() {
    return segments_;
  }
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  @java.lang.Override
  public int getSegmentsCount() {
    return segments_.size();
  }
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  @java.lang.Override
  public samuraibff.proto.SessionTranscriptSegment getSegments(int index) {
    return segments_.get(index);
  }
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  @java.lang.Override
  public samuraibff.proto.SessionTranscriptSegmentOrBuilder getSegmentsOrBuilder(
      int index) {
    return segments_.get(index);
  }

  public static final int FULL_TEXT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fullText_ = "";
  /**
   * <code>string full_text = 6;</code>
   * @return The fullText.
   */
  @java.lang.Override
  public java.lang.String getFullText() {
    java.lang.Object ref = fullText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fullText_ = s;
      return s;
    }
  }
  /**
   * <code>string full_text = 6;</code>
   * @return The bytes for fullText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFullTextBytes() {
    java.lang.Object ref = fullText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 7;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 7;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_NS_FIELD_NUMBER = 8;
  private long createdAtNs_ = 0L;
  /**
   * <code>uint64 created_at_ns = 8;</code>
   * @return The createdAtNs.
   */
  @java.lang.Override
  public long getCreatedAtNs() {
    return createdAtNs_;
  }

  public static final int TRACK_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object trackId_ = "";
  /**
   * <code>string track_id = 9;</code>
   * @return The trackId.
   */
  @java.lang.Override
  public java.lang.String getTrackId() {
    java.lang.Object ref = trackId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      trackId_ = s;
      return s;
    }
  }
  /**
   * <code>string track_id = 9;</code>
   * @return The bytes for trackId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTrackIdBytes() {
    java.lang.Object ref = trackId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      trackId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recordingUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, recordingUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, lang_);
    }
    if (java.lang.Float.floatToRawIntBits(durationS_) != 0) {
      output.writeFloat(4, durationS_);
    }
    for (int i = 0; i < segments_.size(); i++) {
      output.writeMessage(5, segments_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullText_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, fullText_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, tenantId_);
    }
    if (createdAtNs_ != 0L) {
      output.writeUInt64(8, createdAtNs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, trackId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recordingUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, recordingUrl_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lang_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, lang_);
    }
    if (java.lang.Float.floatToRawIntBits(durationS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, durationS_);
    }
    for (int i = 0; i < segments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, segments_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullText_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, fullText_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, tenantId_);
    }
    if (createdAtNs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, createdAtNs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trackId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, trackId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.SessionTranscript)) {
      return super.equals(obj);
    }
    samuraibff.proto.SessionTranscript other = (samuraibff.proto.SessionTranscript) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getRecordingUrl()
        .equals(other.getRecordingUrl())) return false;
    if (!getLang()
        .equals(other.getLang())) return false;
    if (java.lang.Float.floatToIntBits(getDurationS())
        != java.lang.Float.floatToIntBits(
            other.getDurationS())) return false;
    if (!getSegmentsList()
        .equals(other.getSegmentsList())) return false;
    if (!getFullText()
        .equals(other.getFullText())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (getCreatedAtNs()
        != other.getCreatedAtNs()) return false;
    if (!getTrackId()
        .equals(other.getTrackId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + RECORDING_URL_FIELD_NUMBER;
    hash = (53 * hash) + getRecordingUrl().hashCode();
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + getLang().hashCode();
    hash = (37 * hash) + DURATION_S_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDurationS());
    if (getSegmentsCount() > 0) {
      hash = (37 * hash) + SEGMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getSegmentsList().hashCode();
    }
    hash = (37 * hash) + FULL_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getFullText().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + CREATED_AT_NS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAtNs());
    hash = (37 * hash) + TRACK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTrackId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.SessionTranscript parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.SessionTranscript parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.SessionTranscript parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.SessionTranscript parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.SessionTranscript prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SessionTranscript}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SessionTranscript)
      samuraibff.proto.SessionTranscriptOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_SessionTranscript_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_SessionTranscript_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.SessionTranscript.class, samuraibff.proto.SessionTranscript.Builder.class);
    }

    // Construct using samuraibff.proto.SessionTranscript.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      recordingUrl_ = "";
      lang_ = "";
      durationS_ = 0F;
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
      } else {
        segments_ = null;
        segmentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      fullText_ = "";
      tenantId_ = "";
      createdAtNs_ = 0L;
      trackId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_SessionTranscript_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.SessionTranscript getDefaultInstanceForType() {
      return samuraibff.proto.SessionTranscript.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.SessionTranscript build() {
      samuraibff.proto.SessionTranscript result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.SessionTranscript buildPartial() {
      samuraibff.proto.SessionTranscript result = new samuraibff.proto.SessionTranscript(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(samuraibff.proto.SessionTranscript result) {
      if (segmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          segments_ = java.util.Collections.unmodifiableList(segments_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.segments_ = segments_;
      } else {
        result.segments_ = segmentsBuilder_.build();
      }
    }

    private void buildPartial0(samuraibff.proto.SessionTranscript result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.recordingUrl_ = recordingUrl_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lang_ = lang_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.durationS_ = durationS_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.fullText_ = fullText_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.createdAtNs_ = createdAtNs_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.trackId_ = trackId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.SessionTranscript) {
        return mergeFrom((samuraibff.proto.SessionTranscript)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.SessionTranscript other) {
      if (other == samuraibff.proto.SessionTranscript.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRecordingUrl().isEmpty()) {
        recordingUrl_ = other.recordingUrl_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLang().isEmpty()) {
        lang_ = other.lang_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (java.lang.Float.floatToRawIntBits(other.getDurationS()) != 0) {
        setDurationS(other.getDurationS());
      }
      if (segmentsBuilder_ == null) {
        if (!other.segments_.isEmpty()) {
          if (segments_.isEmpty()) {
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSegmentsIsMutable();
            segments_.addAll(other.segments_);
          }
          onChanged();
        }
      } else {
        if (!other.segments_.isEmpty()) {
          if (segmentsBuilder_.isEmpty()) {
            segmentsBuilder_.dispose();
            segmentsBuilder_ = null;
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00000010);
            segmentsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSegmentsFieldBuilder() : null;
          } else {
            segmentsBuilder_.addAllMessages(other.segments_);
          }
        }
      }
      if (!other.getFullText().isEmpty()) {
        fullText_ = other.fullText_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getCreatedAtNs() != 0L) {
        setCreatedAtNs(other.getCreatedAtNs());
      }
      if (!other.getTrackId().isEmpty()) {
        trackId_ = other.trackId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              recordingUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              lang_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 37: {
              durationS_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 42: {
              samuraibff.proto.SessionTranscriptSegment m =
                  input.readMessage(
                      samuraibff.proto.SessionTranscriptSegment.parser(),
                      extensionRegistry);
              if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.add(m);
              } else {
                segmentsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              fullText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              createdAtNs_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              trackId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object recordingUrl_ = "";
    /**
     * <code>string recording_url = 2;</code>
     * @return The recordingUrl.
     */
    public java.lang.String getRecordingUrl() {
      java.lang.Object ref = recordingUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordingUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recording_url = 2;</code>
     * @return The bytes for recordingUrl.
     */
    public com.google.protobuf.ByteString
        getRecordingUrlBytes() {
      java.lang.Object ref = recordingUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordingUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recording_url = 2;</code>
     * @param value The recordingUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRecordingUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recordingUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string recording_url = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordingUrl() {
      recordingUrl_ = getDefaultInstance().getRecordingUrl();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string recording_url = 2;</code>
     * @param value The bytes for recordingUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRecordingUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recordingUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object lang_ = "";
    /**
     * <code>string lang = 3;</code>
     * @return The lang.
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lang = 3;</code>
     * @return The bytes for lang.
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lang = 3;</code>
     * @param value The lang to set.
     * @return This builder for chaining.
     */
    public Builder setLang(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lang_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLang() {
      lang_ = getDefaultInstance().getLang();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string lang = 3;</code>
     * @param value The bytes for lang to set.
     * @return This builder for chaining.
     */
    public Builder setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lang_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private float durationS_ ;
    /**
     * <code>float duration_s = 4;</code>
     * @return The durationS.
     */
    @java.lang.Override
    public float getDurationS() {
      return durationS_;
    }
    /**
     * <code>float duration_s = 4;</code>
     * @param value The durationS to set.
     * @return This builder for chaining.
     */
    public Builder setDurationS(float value) {

      durationS_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float duration_s = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationS() {
      bitField0_ = (bitField0_ & ~0x00000008);
      durationS_ = 0F;
      onChanged();
      return this;
    }

    private java.util.List<samuraibff.proto.SessionTranscriptSegment> segments_ =
      java.util.Collections.emptyList();
    private void ensureSegmentsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        segments_ = new java.util.ArrayList<samuraibff.proto.SessionTranscriptSegment>(segments_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.SessionTranscriptSegment, samuraibff.proto.SessionTranscriptSegment.Builder, samuraibff.proto.SessionTranscriptSegmentOrBuilder> segmentsBuilder_;

    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public java.util.List<samuraibff.proto.SessionTranscriptSegment> getSegmentsList() {
      if (segmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(segments_);
      } else {
        return segmentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public int getSegmentsCount() {
      if (segmentsBuilder_ == null) {
        return segments_.size();
      } else {
        return segmentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public samuraibff.proto.SessionTranscriptSegment getSegments(int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);
      } else {
        return segmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder setSegments(
        int index, samuraibff.proto.SessionTranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.set(index, value);
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder setSegments(
        int index, samuraibff.proto.SessionTranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.set(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder addSegments(samuraibff.proto.SessionTranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder addSegments(
        int index, samuraibff.proto.SessionTranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(index, value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder addSegments(
        samuraibff.proto.SessionTranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder addSegments(
        int index, samuraibff.proto.SessionTranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder addAllSegments(
        java.lang.Iterable<? extends samuraibff.proto.SessionTranscriptSegment> values) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, segments_);
        onChanged();
      } else {
        segmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder clearSegments() {
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        segmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public Builder removeSegments(int index) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.remove(index);
        onChanged();
      } else {
        segmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public samuraibff.proto.SessionTranscriptSegment.Builder getSegmentsBuilder(
        int index) {
      return internalGetSegmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public samuraibff.proto.SessionTranscriptSegmentOrBuilder getSegmentsOrBuilder(
        int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);  } else {
        return segmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public java.util.List<? extends samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
         getSegmentsOrBuilderList() {
      if (segmentsBuilder_ != null) {
        return segmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(segments_);
      }
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public samuraibff.proto.SessionTranscriptSegment.Builder addSegmentsBuilder() {
      return internalGetSegmentsFieldBuilder().addBuilder(
          samuraibff.proto.SessionTranscriptSegment.getDefaultInstance());
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public samuraibff.proto.SessionTranscriptSegment.Builder addSegmentsBuilder(
        int index) {
      return internalGetSegmentsFieldBuilder().addBuilder(
          index, samuraibff.proto.SessionTranscriptSegment.getDefaultInstance());
    }
    /**
     * <code>repeated .SessionTranscriptSegment segments = 5;</code>
     */
    public java.util.List<samuraibff.proto.SessionTranscriptSegment.Builder> 
         getSegmentsBuilderList() {
      return internalGetSegmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        samuraibff.proto.SessionTranscriptSegment, samuraibff.proto.SessionTranscriptSegment.Builder, samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
        internalGetSegmentsFieldBuilder() {
      if (segmentsBuilder_ == null) {
        segmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            samuraibff.proto.SessionTranscriptSegment, samuraibff.proto.SessionTranscriptSegment.Builder, samuraibff.proto.SessionTranscriptSegmentOrBuilder>(
                segments_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        segments_ = null;
      }
      return segmentsBuilder_;
    }

    private java.lang.Object fullText_ = "";
    /**
     * <code>string full_text = 6;</code>
     * @return The fullText.
     */
    public java.lang.String getFullText() {
      java.lang.Object ref = fullText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string full_text = 6;</code>
     * @return The bytes for fullText.
     */
    public com.google.protobuf.ByteString
        getFullTextBytes() {
      java.lang.Object ref = fullText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string full_text = 6;</code>
     * @param value The fullText to set.
     * @return This builder for chaining.
     */
    public Builder setFullText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fullText_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string full_text = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFullText() {
      fullText_ = getDefaultInstance().getFullText();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string full_text = 6;</code>
     * @param value The bytes for fullText to set.
     * @return This builder for chaining.
     */
    public Builder setFullTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fullText_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 7;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 7;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 7;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 7;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private long createdAtNs_ ;
    /**
     * <code>uint64 created_at_ns = 8;</code>
     * @return The createdAtNs.
     */
    @java.lang.Override
    public long getCreatedAtNs() {
      return createdAtNs_;
    }
    /**
     * <code>uint64 created_at_ns = 8;</code>
     * @param value The createdAtNs to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAtNs(long value) {

      createdAtNs_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 created_at_ns = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAtNs() {
      bitField0_ = (bitField0_ & ~0x00000080);
      createdAtNs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object trackId_ = "";
    /**
     * <code>string track_id = 9;</code>
     * @return The trackId.
     */
    public java.lang.String getTrackId() {
      java.lang.Object ref = trackId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trackId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string track_id = 9;</code>
     * @return The bytes for trackId.
     */
    public com.google.protobuf.ByteString
        getTrackIdBytes() {
      java.lang.Object ref = trackId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trackId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string track_id = 9;</code>
     * @param value The trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      trackId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string track_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackId() {
      trackId_ = getDefaultInstance().getTrackId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string track_id = 9;</code>
     * @param value The bytes for trackId to set.
     * @return This builder for chaining.
     */
    public Builder setTrackIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      trackId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SessionTranscript)
  }

  // @@protoc_insertion_point(class_scope:SessionTranscript)
  private static final samuraibff.proto.SessionTranscript DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.SessionTranscript();
  }

  public static samuraibff.proto.SessionTranscript getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SessionTranscript>
      PARSER = new com.google.protobuf.AbstractParser<SessionTranscript>() {
    @java.lang.Override
    public SessionTranscript parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SessionTranscript> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SessionTranscript> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.SessionTranscript getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

