// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface SessionTranscriptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SessionTranscript)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string recording_url = 2;</code>
   * @return The recordingUrl.
   */
  java.lang.String getRecordingUrl();
  /**
   * <code>string recording_url = 2;</code>
   * @return The bytes for recordingUrl.
   */
  com.google.protobuf.ByteString
      getRecordingUrlBytes();

  /**
   * <code>string lang = 3;</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 3;</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>float duration_s = 4;</code>
   * @return The durationS.
   */
  float getDurationS();

  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  java.util.List<samuraibff.proto.SessionTranscriptSegment> 
      getSegmentsList();
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  samuraibff.proto.SessionTranscriptSegment getSegments(int index);
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  int getSegmentsCount();
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  java.util.List<? extends samuraibff.proto.SessionTranscriptSegmentOrBuilder> 
      getSegmentsOrBuilderList();
  /**
   * <code>repeated .SessionTranscriptSegment segments = 5;</code>
   */
  samuraibff.proto.SessionTranscriptSegmentOrBuilder getSegmentsOrBuilder(
      int index);

  /**
   * <code>string full_text = 6;</code>
   * @return The fullText.
   */
  java.lang.String getFullText();
  /**
   * <code>string full_text = 6;</code>
   * @return The bytes for fullText.
   */
  com.google.protobuf.ByteString
      getFullTextBytes();

  /**
   * <code>string tenant_id = 7;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 7;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>uint64 created_at_ns = 8;</code>
   * @return The createdAtNs.
   */
  long getCreatedAtNs();

  /**
   * <code>string track_id = 9;</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <code>string track_id = 9;</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();
}
