// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public final class StreamProto extends com.google.protobuf.GeneratedFile {
  private StreamProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "StreamProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AudioChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AudioChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AsrEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AsrEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DiarEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DiarEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RefinedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RefinedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingFinished_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RecordingFinished_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WordAlignment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WordAlignment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FinalEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FinalEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SessionTranscriptSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SessionTranscriptSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SessionTranscript_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SessionTranscript_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014stream.proto\"\234\001\n\nAudioChunk\022\022\n\nsession" +
      "_id\030\001 \001(\t\022\013\n\003seq\030\002 \001(\004\022\r\n\005t0_ns\030\003 \001(\003\022\023\n" +
      "\013sample_rate\030\004 \001(\r\022\020\n\010pcm16_le\030\005 \001(\014\022\014\n\004" +
      "lang\030\006 \001(\t\022\026\n\016bff_origin_uri\030\007 \001(\t\022\021\n\tte" +
      "nant_id\030\010 \001(\t\"\203\001\n\010AsrEvent\022\022\n\nsession_id" +
      "\030\001 \001(\t\022\017\n\007start_s\030\002 \001(\001\022\r\n\005end_s\030\003 \001(\001\022\014" +
      "\n\004text\030\004 \001(\t\022\026\n\004type\030\005 \001(\0162\010.AsrType\022\014\n\004" +
      "lang\030\006 \001(\t\022\017\n\007speaker\030\007 \001(\t\"d\n\tDiarEvent" +
      "\022\022\n\nsession_id\030\001 \001(\t\022\017\n\007start_s\030\002 \001(\001\022\r\n" +
      "\005end_s\030\003 \001(\001\022\017\n\007speaker\030\004 \001(\t\022\022\n\nconfide" +
      "nce\030\005 \001(\002\"\262\001\n\014RefinedEvent\022\022\n\nsession_id" +
      "\030\001 \001(\t\022\017\n\007start_s\030\002 \001(\001\022\r\n\005end_s\030\003 \001(\001\022\014" +
      "\n\004text\030\004 \001(\t\022\017\n\007speaker\030\005 \001(\t\022\026\n\016superse" +
      "des_seq\030\006 \003(\004\022\014\n\004lang\030\007 \001(\t\022\026\n\016bff_origi" +
      "n_uri\030\010 \001(\t\022\021\n\ttenant_id\030\t \001(\t\"\237\001\n\021Recor" +
      "dingFinished\022\022\n\nsession_id\030\001 \001(\t\022\025\n\rreco" +
      "rding_url\030\002 \001(\t\022\022\n\nduration_s\030\003 \001(\001\022\023\n\013s" +
      "ample_rate\030\004 \001(\005\022\014\n\004lang\030\005 \001(\t\022\021\n\ttenant" +
      "_id\030\006 \001(\t\022\025\n\rcreated_at_ns\030\007 \001(\003\"=\n\rWord" +
      "Alignment\022\017\n\007start_s\030\001 \001(\001\022\r\n\005end_s\030\002 \001(" +
      "\001\022\014\n\004text\030\003 \001(\t\"\214\001\n\nFinalEvent\022\022\n\nsessio" +
      "n_id\030\001 \001(\t\022\017\n\007start_s\030\002 \001(\001\022\r\n\005end_s\030\003 \001" +
      "(\001\022\014\n\004text\030\004 \001(\t\022\017\n\007speaker\030\005 \001(\t\022\014\n\004lan" +
      "g\030\006 \001(\t\022\035\n\005words\030\007 \003(\0132\016.WordAlignment\"x" +
      "\n\030SessionTranscriptSegment\022\017\n\007start_s\030\001 " +
      "\001(\001\022\r\n\005end_s\030\002 \001(\001\022\014\n\004text\030\003 \001(\t\022\017\n\007spea" +
      "ker\030\004 \001(\t\022\035\n\005words\030\005 \003(\0132\016.WordAlignment" +
      "\"\312\001\n\021SessionTranscript\022\022\n\nsession_id\030\001 \001" +
      "(\t\022\025\n\rrecording_url\030\002 \001(\t\022\014\n\004lang\030\003 \001(\t\022" +
      "\022\n\nduration_s\030\004 \001(\002\022+\n\010segments\030\005 \003(\0132\031." +
      "SessionTranscriptSegment\022\021\n\tfull_text\030\006 " +
      "\001(\t\022\021\n\ttenant_id\030\007 \001(\t\022\025\n\rcreated_at_ns\030" +
      "\010 \001(\004*!\n\007AsrType\022\013\n\007PARTIAL\020\000\022\t\n\005FINAL\020\001" +
      "23\n\013RealtimeASR\022$\n\006Stream\022\013.AudioChunk\032\t" +
      ".AsrEvent(\0010\001B!\n\020samuraibff.protoB\013Strea" +
      "mProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AudioChunk_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_AudioChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AudioChunk_descriptor,
        new java.lang.String[] { "SessionId", "Seq", "T0Ns", "SampleRate", "Pcm16Le", "Lang", "BffOriginUri", "TenantId", });
    internal_static_AsrEvent_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_AsrEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AsrEvent_descriptor,
        new java.lang.String[] { "SessionId", "StartS", "EndS", "Text", "Type", "Lang", "Speaker", });
    internal_static_DiarEvent_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_DiarEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DiarEvent_descriptor,
        new java.lang.String[] { "SessionId", "StartS", "EndS", "Speaker", "Confidence", });
    internal_static_RefinedEvent_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_RefinedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RefinedEvent_descriptor,
        new java.lang.String[] { "SessionId", "StartS", "EndS", "Text", "Speaker", "SupersedesSeq", "Lang", "BffOriginUri", "TenantId", });
    internal_static_RecordingFinished_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_RecordingFinished_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RecordingFinished_descriptor,
        new java.lang.String[] { "SessionId", "RecordingUrl", "DurationS", "SampleRate", "Lang", "TenantId", "CreatedAtNs", });
    internal_static_WordAlignment_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_WordAlignment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_WordAlignment_descriptor,
        new java.lang.String[] { "StartS", "EndS", "Text", });
    internal_static_FinalEvent_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_FinalEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FinalEvent_descriptor,
        new java.lang.String[] { "SessionId", "StartS", "EndS", "Text", "Speaker", "Lang", "Words", });
    internal_static_SessionTranscriptSegment_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_SessionTranscriptSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SessionTranscriptSegment_descriptor,
        new java.lang.String[] { "StartS", "EndS", "Text", "Speaker", "Words", });
    internal_static_SessionTranscript_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_SessionTranscript_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SessionTranscript_descriptor,
        new java.lang.String[] { "SessionId", "RecordingUrl", "Lang", "DurationS", "Segments", "FullText", "TenantId", "CreatedAtNs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
