// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

/**
 * Protobuf type {@code WordAlignment}
 */
@com.google.protobuf.Generated
public final class WordAlignment extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:WordAlignment)
    WordAlignmentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "WordAlignment");
  }
  // Use WordAlignment.newBuilder() to construct.
  private WordAlignment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WordAlignment() {
    text_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return samuraibff.proto.StreamProto.internal_static_WordAlignment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return samuraibff.proto.StreamProto.internal_static_WordAlignment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            samuraibff.proto.WordAlignment.class, samuraibff.proto.WordAlignment.Builder.class);
  }

  public static final int START_S_FIELD_NUMBER = 1;
  private double startS_ = 0D;
  /**
   * <pre>
   * absolute word start time in seconds
   * </pre>
   *
   * <code>double start_s = 1 [json_name = "startS"];</code>
   * @return The startS.
   */
  @java.lang.Override
  public double getStartS() {
    return startS_;
  }

  public static final int END_S_FIELD_NUMBER = 2;
  private double endS_ = 0D;
  /**
   * <pre>
   * absolute word end time in seconds
   * </pre>
   *
   * <code>double end_s = 2 [json_name = "endS"];</code>
   * @return The endS.
   */
  @java.lang.Override
  public double getEndS() {
    return endS_;
  }

  public static final int TEXT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <pre>
   * the word text (normalized)
   * </pre>
   *
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the word text (normalized)
   * </pre>
   *
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(startS_) != 0) {
      output.writeDouble(1, startS_);
    }
    if (java.lang.Double.doubleToRawLongBits(endS_) != 0) {
      output.writeDouble(2, endS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, text_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(startS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, startS_);
    }
    if (java.lang.Double.doubleToRawLongBits(endS_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, endS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, text_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof samuraibff.proto.WordAlignment)) {
      return super.equals(obj);
    }
    samuraibff.proto.WordAlignment other = (samuraibff.proto.WordAlignment) obj;

    if (java.lang.Double.doubleToLongBits(getStartS())
        != java.lang.Double.doubleToLongBits(
            other.getStartS())) return false;
    if (java.lang.Double.doubleToLongBits(getEndS())
        != java.lang.Double.doubleToLongBits(
            other.getEndS())) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + START_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getStartS()));
    hash = (37 * hash) + END_S_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEndS()));
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static samuraibff.proto.WordAlignment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.WordAlignment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.WordAlignment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.WordAlignment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.WordAlignment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static samuraibff.proto.WordAlignment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static samuraibff.proto.WordAlignment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.WordAlignment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static samuraibff.proto.WordAlignment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static samuraibff.proto.WordAlignment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static samuraibff.proto.WordAlignment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static samuraibff.proto.WordAlignment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(samuraibff.proto.WordAlignment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WordAlignment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WordAlignment)
      samuraibff.proto.WordAlignmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return samuraibff.proto.StreamProto.internal_static_WordAlignment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return samuraibff.proto.StreamProto.internal_static_WordAlignment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              samuraibff.proto.WordAlignment.class, samuraibff.proto.WordAlignment.Builder.class);
    }

    // Construct using samuraibff.proto.WordAlignment.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      startS_ = 0D;
      endS_ = 0D;
      text_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return samuraibff.proto.StreamProto.internal_static_WordAlignment_descriptor;
    }

    @java.lang.Override
    public samuraibff.proto.WordAlignment getDefaultInstanceForType() {
      return samuraibff.proto.WordAlignment.getDefaultInstance();
    }

    @java.lang.Override
    public samuraibff.proto.WordAlignment build() {
      samuraibff.proto.WordAlignment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public samuraibff.proto.WordAlignment buildPartial() {
      samuraibff.proto.WordAlignment result = new samuraibff.proto.WordAlignment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(samuraibff.proto.WordAlignment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.startS_ = startS_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endS_ = endS_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.text_ = text_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof samuraibff.proto.WordAlignment) {
        return mergeFrom((samuraibff.proto.WordAlignment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(samuraibff.proto.WordAlignment other) {
      if (other == samuraibff.proto.WordAlignment.getDefaultInstance()) return this;
      if (java.lang.Double.doubleToRawLongBits(other.getStartS()) != 0) {
        setStartS(other.getStartS());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getEndS()) != 0) {
        setEndS(other.getEndS());
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              startS_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              endS_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double startS_ ;
    /**
     * <pre>
     * absolute word start time in seconds
     * </pre>
     *
     * <code>double start_s = 1 [json_name = "startS"];</code>
     * @return The startS.
     */
    @java.lang.Override
    public double getStartS() {
      return startS_;
    }
    /**
     * <pre>
     * absolute word start time in seconds
     * </pre>
     *
     * <code>double start_s = 1 [json_name = "startS"];</code>
     * @param value The startS to set.
     * @return This builder for chaining.
     */
    public Builder setStartS(double value) {

      startS_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * absolute word start time in seconds
     * </pre>
     *
     * <code>double start_s = 1 [json_name = "startS"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStartS() {
      bitField0_ = (bitField0_ & ~0x00000001);
      startS_ = 0D;
      onChanged();
      return this;
    }

    private double endS_ ;
    /**
     * <pre>
     * absolute word end time in seconds
     * </pre>
     *
     * <code>double end_s = 2 [json_name = "endS"];</code>
     * @return The endS.
     */
    @java.lang.Override
    public double getEndS() {
      return endS_;
    }
    /**
     * <pre>
     * absolute word end time in seconds
     * </pre>
     *
     * <code>double end_s = 2 [json_name = "endS"];</code>
     * @param value The endS to set.
     * @return This builder for chaining.
     */
    public Builder setEndS(double value) {

      endS_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * absolute word end time in seconds
     * </pre>
     *
     * <code>double end_s = 2 [json_name = "endS"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEndS() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endS_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <pre>
     * the word text (normalized)
     * </pre>
     *
     * <code>string text = 3 [json_name = "text"];</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the word text (normalized)
     * </pre>
     *
     * <code>string text = 3 [json_name = "text"];</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the word text (normalized)
     * </pre>
     *
     * <code>string text = 3 [json_name = "text"];</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the word text (normalized)
     * </pre>
     *
     * <code>string text = 3 [json_name = "text"];</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the word text (normalized)
     * </pre>
     *
     * <code>string text = 3 [json_name = "text"];</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:WordAlignment)
  }

  // @@protoc_insertion_point(class_scope:WordAlignment)
  private static final samuraibff.proto.WordAlignment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new samuraibff.proto.WordAlignment();
  }

  public static samuraibff.proto.WordAlignment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WordAlignment>
      PARSER = new com.google.protobuf.AbstractParser<WordAlignment>() {
    @java.lang.Override
    public WordAlignment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WordAlignment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WordAlignment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public samuraibff.proto.WordAlignment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

