// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stream.proto
// Protobuf Java Version: 4.33.4

package samuraibff.proto;

@com.google.protobuf.Generated
public interface WordAlignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WordAlignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * absolute word start time in seconds
   * </pre>
   *
   * <code>double start_s = 1;</code>
   * @return The startS.
   */
  double getStartS();

  /**
   * <pre>
   * absolute word end time in seconds
   * </pre>
   *
   * <code>double end_s = 2;</code>
   * @return The endS.
   */
  double getEndS();

  /**
   * <pre>
   * the word text (normalized)
   * </pre>
   *
   * <code>string text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * the word text (normalized)
   * </pre>
   *
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
